// SPDX-License-Identifier: MPL-2.0
//! Self-contained HTML scorecard report.
//!
//! `to_html` renders one `.html` file with inline CSS and no external
//! requests, so it works from `file://` and from any static server.
//! It mirrors the linear-flow visual language: pipeline strip, in/out
//! chips, terminal-styled runs, and pass/fail pills.

use sc_core::Scorecard;

use super::{
    coverage_measured, diff_baseline, evidence_functions, plural, provided, raw_log, rest_of_tree,
    Outcome, COVERAGE_NOT_MEASURED,
};

pub fn to_html(card: &Scorecard) -> String {
    let mut out = String::new();
    out.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\"/>\n");
    out.push_str(
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n<title>",
    );
    out.push_str(&esc(&format!(
        "scorecard: {} — {}",
        card.repo,
        Outcome::of(card).word(card)
    )));
    out.push_str("</title>\n<style>\n");
    out.push_str(CSS);
    out.push_str("\n</style>\n</head>\n<body>\n<main>\n");
    hero(&mut out, card);
    pipeline(&mut out, card);
    scores_metrics(&mut out, card);
    a11y_section(&mut out, card);
    gates(&mut out, card);
    crap(&mut out, card);
    generated_files_warning(&mut out, card);
    findings(&mut out, card);
    llm_section(&mut out, card);
    deep(&mut out, card);
    runs(&mut out, card);
    out.push_str("<footer>generated by <code>sc analyze --format html</code> · scorecard ");
    out.push_str(&esc(&card.id));
    out.push_str(" · schema ");
    out.push_str(&esc(&card.version));
    out.push_str("</footer>\n</main>\n</body>\n</html>\n");
    out
}

fn generated_files_warning(out: &mut String, card: &Scorecard) {
    let Some(warning) = card.generated_files_warning.as_ref() else {
        return;
    };
    out.push_str("<h2>generated files analyzed</h2>\n<div class=\"card\"><p>");
    out.push_str(&esc(&warning.suggested_action));
    out.push_str("</p><ul class=\"pathlist\">");
    for file in &warning.files {
        out.push_str("<li><code>");
        out.push_str(&esc(file));
        out.push_str("</code></li>");
    }
    out.push_str("</ul></div>\n");
}

const CSS: &str = r#"
:root{--bg:#070b14;--card:#0b1428;--line:#22314f;--ink:#e8eefc;--dim:#8fa1c7;
--accent:#6ea8ff;--ok:#59e3a5;--bad:#ff7a90;--warn:#ffcf6e}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
main{padding:28px clamp(12px,3vw,40px) 60px}
h1{font-size:22px;margin:0}
h2{font-size:15px;margin:28px 0 10px;color:var(--dim);text-transform:uppercase;
letter-spacing:.08em}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;
padding:16px 18px;margin-top:12px}
.hero{display:flex;gap:16px;align-items:center;flex-wrap:wrap}
.hero>div{flex:1 1 220px;min-width:0;overflow-wrap:anywhere}
.verdict{font-size:15px;font-weight:800;border-radius:999px;padding:8px 22px;
letter-spacing:.06em}
.verdict.pass{background:rgba(89,227,165,.14);color:var(--ok);
border:1px solid var(--ok)}
.verdict.fail{background:rgba(255,122,144,.12);color:var(--bad);
border:1px solid var(--bad)}
.verdict.report{background:rgba(110,168,255,.12);color:#c9d9ff;
border:1px solid var(--accent)}
details{margin-top:4px}
summary{cursor:pointer;color:var(--accent);font-size:12px}
.group{margin-top:12px}
.group>summary{font-size:14px;color:var(--ink);padding:6px 0}
.group>summary .pill{margin-left:4px}
.more{color:var(--dim);font-size:12.5px;margin:10px 0 0}
.fnlist{margin:6px 0 0;padding-left:18px;font-size:12.5px;color:var(--dim)}
.fnlist .more{list-style:none;margin-left:-18px}
.log pre{background:#04080f;border:1px solid #1b2a4e;border-radius:10px;
padding:8px 12px;margin:6px 0 0;font-family:ui-monospace,Menlo,monospace;
font-size:11.5px;max-height:320px;overflow:auto;white-space:pre}
.pathlist{margin-top:6px;max-height:240px;overflow:auto}
.pathlist div{margin:1px 0}
.pathlist code{word-break:normal}
.meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));
gap:8px 20px;margin-top:14px;font-size:12.5px;color:var(--dim)}
.meta>div{min-width:0;overflow:hidden}
.meta b{color:var(--ink);font-weight:600}
.meta code{display:block;max-width:100%;overflow-wrap:anywhere;word-break:break-all}
.meta code,.card code{background:#16223f;padding:1px 6px;border-radius:6px;
font-size:11.5px;color:var(--ink)}
.flow{display:flex;align-items:stretch;gap:0;margin-top:12px;flex-wrap:wrap}
.step{flex:1 1 0;min-width:120px;background:var(--card);
border:1px solid var(--line);border-radius:10px;padding:10px 12px;font-size:12px}
.step b{display:block;font-size:12.5px;margin-bottom:2px}
.step span{color:var(--dim);font-size:11.5px}
.step.hi{border-color:var(--accent)}
.sep{align-self:center;color:#3a5086;font-size:18px;padding:0 6px}
.pill{display:inline-block;font-size:11px;border-radius:999px;
padding:2px 10px;border:1px solid #3a5086;color:#bcd0ff;white-space:nowrap}
.pill.pass{border-color:var(--ok);color:var(--ok)}
.pill.fail{border-color:var(--bad);color:var(--bad)}
.pill.warn{border-color:var(--warn);color:var(--warn)}
.pill.info{border-color:var(--accent);color:#c9d9ff}
.pill.dim{color:var(--dim)}
table{width:100%;border-collapse:collapse;font-size:12.5px}
.card:has(>table){overflow-x:auto}
th{text-align:left;color:var(--dim);font-weight:600;font-size:11px;
text-transform:uppercase;letter-spacing:.06em;padding:6px 8px;
border-bottom:1px solid var(--line)}
td{padding:7px 8px;border-bottom:1px solid #16223f;vertical-align:top}
tr:last-child td{border-bottom:none}
.bar{height:8px;border-radius:4px;background:#16223f;overflow:hidden;
min-width:90px}
.bar i{display:block;height:100%;border-radius:4px}
.cov{display:block;font-size:11.5px;color:var(--dim);margin-top:3px}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));
gap:10px;margin-top:12px}
.tile{background:var(--card);border:1px solid var(--line);border-radius:12px;
padding:10px 14px}
.tile b{display:block;font-size:20px}
.tile span{font-size:11px;color:var(--dim)}
.finding{border-left:4px solid var(--warn)}
.finding.error{border-left-color:var(--bad)}
.finding h3{margin:0 0 6px;font-size:13px;font-family:ui-monospace,Menlo,monospace;
font-weight:600;word-break:break-all}
.finding p{margin:6px 0;font-size:13px}
.finding .row{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:6px}
.suggest{color:var(--dim);font-size:12.5px}
.term{background:#04080f;border:1px solid #1b2a4e;border-radius:10px;
padding:8px 12px;margin:8px 0 0;font-family:ui-monospace,Menlo,monospace;
font-size:11.5px;overflow-x:auto;white-space:nowrap}
.term b{color:var(--ok)}
td.cmd{width:100%;max-width:0}
footer{margin-top:32px;color:var(--dim);font-size:11.5px;text-align:center}
@media (max-width:600px){.card{padding:12px}th,td{padding:6px 5px}
.bar{min-width:48px}}
"#;

fn hero(out: &mut String, card: &Scorecard) {
    let outcome = Outcome::of(card);
    let (cls, label) = match outcome {
        Outcome::Fail => ("fail", "FAIL"),
        Outcome::ReportOnly(_) => ("report", "REPORT ONLY"),
        Outcome::Pass | Outcome::Advisory(_) => ("pass", "PASS"),
    };
    out.push_str("<h1>scorecard</h1>\n<div class=\"card\"><div class=\"hero\">");
    out.push_str(&format!(
        "<span class=\"verdict {cls}\">{}</span>",
        esc(label)
    ));
    out.push_str("<div><div style=\"font-size:16px;font-weight:700\">");
    out.push_str(&esc(&card.repo));
    out.push_str("</div><div style=\"font-size:12px;color:var(--dim)\">pack <code>");
    out.push_str(&esc(&card.pack));
    out.push_str("</code> · scope <code>");
    out.push_str(&esc(&card.scope.mode));
    out.push_str("</code> · <code>");
    out.push_str(&esc(&card.id));
    out.push_str("</code>");
    if let Some(note) = outcome.note() {
        out.push_str(" · ");
        out.push_str(&note);
    }
    out.push_str("</div></div></div><div class=\"meta\">");
    meta(out, "git", &git(card));
    meta(out, "tests", &esc(&card.test_selection));
    meta(
        out,
        "engines run",
        &esc(&if card.engines_run.is_empty() {
            "—".into()
        } else {
            card.engines_run.join(", ")
        }),
    );
    meta(
        out,
        "engines skipped",
        &esc(&if card.engines_skipped.is_empty() {
            "—".into()
        } else {
            card.engines_skipped.join(", ")
        }),
    );
    if let Some(intent) = &card.intent {
        if !intent.trim().is_empty() {
            meta(out, "intent", &esc(intent.trim()));
        }
    }
    if !card.scope.paths.is_empty() {
        meta(out, "paths", &paths(card));
    }
    if let Some(line) = rest_of_tree(card) {
        meta(out, "rest of tree", &esc(&line));
    }
    out.push_str("</div></div>\n");
}

/// Tree scope lists every file in the tree, which buries the report.
/// Collapse tree scope (or long lists) behind a count plus a <details>
/// list; paths break after `/` via <wbr> so lines never split mid-segment.
fn paths(card: &Scorecard) -> String {
    let total = card.scope.paths.len();
    if card.scope.mode != "tree" && total <= 10 {
        return esc(&card.scope.paths.join(", "));
    }
    let mut out = format!(
        "{} {} <details><summary>full list</summary><div class=\"pathlist\">",
        total,
        if total == 1 { "path" } else { "paths" }
    );
    for path in &card.scope.paths {
        out.push_str("<div><code>");
        let mut first = true;
        for segment in path.split('/') {
            if !first {
                out.push_str("/<wbr>");
            }
            out.push_str(&esc(segment));
            first = false;
        }
        out.push_str("</code></div>");
    }
    out.push_str("</div></details>");
    out
}

fn meta(out: &mut String, label: &str, value: &str) {
    out.push_str("<div><b>");
    out.push_str(label);
    out.push_str("</b><br/>");
    out.push_str(value);
    out.push_str("</div>");
}

fn git(card: &Scorecard) -> String {
    let state = esc(&card.git.status_label());
    let changed_paths = card.git.changed_paths_label();
    let changed_paths = if changed_paths.is_empty() {
        String::new()
    } else {
        format!("<br/>changed: {}", esc(&changed_paths))
    };
    match card.git.head.as_deref().filter(|head| !head.is_empty()) {
        // Long SHAs overflow the header meta column, so show a short SHA
        // with the full one on hover. The <code> wrapper keeps the cell
        // inside its column via break-all wrapping.
        Some(head) => {
            let short: String = head.chars().take(12).collect();
            format!(
                "<code title=\"{}\">{} ({})</code>{changed_paths}",
                esc(head),
                esc(&short),
                state
            )
        }
        _ => format!("<code>none ({state})</code>{changed_paths}"),
    }
}

fn pipeline(out: &mut String, card: &Scorecard) {
    let provided: Vec<_> = card.gates.iter().filter(|gate| provided(gate)).collect();
    let passed = provided.iter().filter(|gate| gate.pass).count();
    let ratio = if provided.is_empty() {
        "n/a".to_string()
    } else {
        format!("{passed}/{} pass", provided.len())
    };
    out.push_str("<h2>flow</h2>\n<div class=\"flow\">");
    let scope = match (
        card.scope.mode.as_str(),
        card.scope.paths.len(),
        card.scope.other_paths,
    ) {
        ("diff", n, Some(other)) => format!(
            "diff · {n} path{}; {other} other",
            if n == 1 { "" } else { "s" }
        ),
        (_, 0, _) => card.scope.mode.clone(),
        (_, 1, _) => format!("{} · 1 path", card.scope.mode),
        (_, n, _) => format!("{} · {n} paths", card.scope.mode),
    };
    step(out, "scope", &scope, 0, false);
    step(out, "pack", &card.pack, 0, false);
    step(
        out,
        "engines",
        &format!("{} run", card.engines_run.len()),
        card.engines_skipped.len(),
        false,
    );
    step(out, "gates", &ratio, 0, true);
    out.push_str("<div class=\"sep\">→</div>");
    out.push_str("<div class=\"step");
    let outcome = Outcome::of(card);
    if matches!(outcome, Outcome::Pass | Outcome::Advisory(_)) {
        out.push_str(" hi");
    }
    out.push_str("\"><b>verdict</b><span>");
    out.push_str(&esc(outcome.word(card)));
    out.push_str("</span></div></div>\n");
}

fn step(out: &mut String, title: &str, main: &str, skipped: usize, hi: bool) {
    if !out.ends_with("<div class=\"flow\">") {
        out.push_str("<div class=\"sep\">→</div>");
    }
    out.push_str("<div class=\"step");
    if hi {
        out.push_str(" hi");
    }
    out.push_str("\"><b>");
    out.push_str(title);
    out.push_str("</b><span>");
    out.push_str(&esc(main));
    if skipped > 0 {
        out.push_str(&format!(" · {skipped} skipped"));
    }
    out.push_str("</span></div>");
}

fn a11y_section(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>accessibility</h2>\n<div class=\"card\">");
    let rules = a11y_rules(card);
    if rules.is_empty() {
        out.push_str("<p style=\"color:var(--dim)\">No accessibility findings.</p></div>\n");
        return;
    }
    for rule in rules {
        write_a11y_rule(out, card, rule);
    }
    out.push_str("</div>\n");
}

fn a11y_rules(card: &Scorecard) -> Vec<&str> {
    let mut rules = Vec::new();
    for finding in card
        .findings
        .iter()
        .filter(|finding| finding.engine == "a11y")
    {
        if !rules.contains(&finding.rule.as_str()) {
            rules.push(finding.rule.as_str());
        }
    }
    rules
}

fn write_a11y_rule(out: &mut String, card: &Scorecard, rule: &str) {
    out.push_str("<h3><code>");
    out.push_str(&esc(rule));
    out.push_str("</code></h3><ul>");
    for finding in card.findings.iter().filter(|finding| finding.rule == rule) {
        write_a11y_item(out, finding);
    }
    out.push_str("</ul>");
}

fn write_a11y_item(out: &mut String, finding: &sc_core::Finding) {
    let line = finding
        .span
        .as_ref()
        .map(|span| span.start_line)
        .unwrap_or(1);
    out.push_str("<li><code>");
    out.push_str(&esc(&format!("{}:{line}", finding.file)));
    out.push_str("</code> ");
    out.push_str(&esc(&finding.message));
    out.push_str("</li>");
}

fn scores_metrics(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>scores</h2>\n<div class=\"card\"><table>");
    for (label, value) in [
        ("correctness", card.scores.correctness),
        ("efficiency", card.scores.efficiency),
        ("maintainability", card.scores.maintainability),
        ("security", card.scores.security),
        ("a11y", card.scores.a11y),
    ] {
        let pct = (value.clamp(0.0, 1.0) * 100.0).round() as i64;
        out.push_str(&format!(
            "<tr><td style=\"width:140px\">{label}</td><td><div class=\"bar\"><i style=\"width:{pct}%;background:{}\"></i></div></td><td style=\"width:60px\">{value:.2}</td></tr>",
            score_color(value)
        ));
    }
    out.push_str("</table></div>\n<div class=\"tiles\">");
    tile(out, card.metrics.loc_changed.to_string(), "loc changed");
    tile(out, card.metrics.files_changed.to_string(), "files changed");
    if coverage_measured(card) {
        tile(
            out,
            format!("{:.0}%", card.metrics.coverage_changed * 100.0),
            "coverage",
        );
    } else {
        tile(out, "—".into(), "coverage not measured");
    }
    tile(out, fmt_num(card.metrics.crap_max), "crap max");
    tile(
        out,
        card.metrics.crap_over_threshold.to_string(),
        "over threshold",
    );
    tile(
        out,
        card.metrics.undeclared_dependencies.to_string(),
        "undeclared deps",
    );
    if card.metrics.hallucinated_imports > 0 {
        tile(
            out,
            card.metrics.hallucinated_imports.to_string(),
            "hallucinated imports",
        );
    }
    out.push_str("</div>\n");
}

fn tile(out: &mut String, value: String, label: &str) {
    out.push_str("<div class=\"tile\"><b>");
    out.push_str(&esc(&value));
    out.push_str("</b><span>");
    out.push_str(label);
    out.push_str("</span></div>");
}

fn gates(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>gates</h2>\n<div class=\"card\"><table>");
    out.push_str("<tr><th>gate</th><th>result</th><th>enforced</th><th>reason</th></tr>");
    for gate in &card.gates {
        out.push_str("<tr><td><code>");
        out.push_str(&esc(&gate.id));
        out.push_str("</code></td><td>");
        if !provided(gate) {
            out.push_str("<span class=\"pill dim\">skipped</span>");
        } else if gate.pass {
            out.push_str("<span class=\"pill pass\">pass</span>");
        } else {
            out.push_str("<span class=\"pill fail\">fail</span>");
        }
        out.push_str("</td><td>");
        if gate.enforced {
            out.push_str("yes");
        } else {
            out.push_str("<span class=\"pill dim\">reported only</span>");
        }
        out.push_str("</td><td>");
        out.push_str(&esc(gate.reason.as_deref().unwrap_or("")));
        out.push_str("</td></tr>");
    }
    out.push_str("</table></div>\n");
}

fn crap(out: &mut String, card: &Scorecard) {
    let measured = coverage_measured(card);
    out.push_str("<h2>worst crap · threshold ");
    out.push_str(&card.crap.threshold.to_string());
    out.push_str("</h2>\n<div class=\"card\">");
    if let Some(line) = rest_of_tree(card) {
        out.push_str("<p style=\"color:var(--dim);margin:0 0 8px\">");
        out.push_str(&esc(&line));
        out.push_str("</p>");
    }
    if let Some(line) = diff_baseline(card) {
        out.push_str("<p style=\"color:var(--dim);margin:0 0 8px\">");
        out.push_str(&esc(&line));
        out.push_str("</p>");
    }
    if !measured {
        out.push_str("<p style=\"color:var(--dim);margin:0 0 8px\">");
        out.push_str(COVERAGE_NOT_MEASURED);
        out.push_str("</p>");
    }
    out.push_str("<table>");
    out.push_str("<tr><th>crap</th><th>cc</th><th>coverage</th><th>symbol</th><th>file</th></tr>");
    if card.crap.worst.is_empty() {
        let empty = if measured {
            "No functions over the reporting window."
        } else {
            "No CRAP scores: coverage was not measured."
        };
        out.push_str("<tr><td colspan=\"5\" style=\"color:var(--dim)\">");
        out.push_str(empty);
        out.push_str("</td></tr>");
    }
    for row in &card.crap.worst {
        let over = row.crap > card.crap.threshold as f64;
        let cov = (row.coverage.clamp(0.0, 1.0) * 100.0).round() as i64;
        out.push_str("<tr><td><span class=\"pill ");
        out.push_str(if over { "fail" } else { "pass" });
        out.push_str("\">");
        out.push_str(&esc(&fmt_num(row.crap)));
        out.push_str("</span></td><td>");
        out.push_str(&row.cc.to_string());
        if measured {
            out.push_str("</td><td><div class=\"bar\"><i style=\"width:");
            out.push_str(&cov.to_string());
            out.push_str("%;background:");
            out.push_str(score_color(row.coverage));
            out.push_str("\"></i></div>");
            out.push_str(&format!("<span class=\"cov\">{cov}%</span>"));
        } else {
            out.push_str("</td><td><span class=\"cov\">not measured</span>");
        }
        out.push_str("</td><td><code>");
        out.push_str(&esc(&row.symbol));
        out.push_str("</code></td><td><code>");
        out.push_str(&esc(&row.file));
        out.push_str("</code></td></tr>");
    }
    out.push_str("</table></div>\n");
}

/// Cards shown per rule group. The rest stay in the JSON and SARIF reports,
/// so a tree with a thousand CRAP findings does not become a megabyte page.
const GROUP_LIMIT: usize = 50;

/// Error groups at or under this size start expanded.
const OPEN_LIMIT: usize = 10;

/// Findings grouped by rule so one test failure is not buried under a
/// hundred CRAP cards. Groups holding errors come first, smallest first,
/// since a rare error is usually the one to act on; small error groups
/// start open and the rest are collapsed behind their counts. `complexity.untested` repeats
/// `crap.over_threshold` for the same function, so it folds into that
/// card. Accessibility findings already have their own section above.
fn findings(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>findings · ");
    out.push_str(&card.findings.len().to_string());
    out.push_str("</h2>\n");
    if card.findings.is_empty() {
        out.push_str("<div class=\"card\" style=\"color:var(--dim)\">None. Clean gate.</div>\n");
        return;
    }
    let key = |finding: &sc_core::Finding| (finding.file.clone(), finding.symbol.clone());
    let crap_keys: Vec<_> = card
        .findings
        .iter()
        .filter(|finding| finding.rule == "crap.over_threshold")
        .map(key)
        .collect();
    let folded = |finding: &sc_core::Finding| {
        finding.rule == "complexity.untested"
            && finding.symbol.is_some()
            && crap_keys.contains(&key(finding))
    };
    let untested: Vec<_> = card
        .findings
        .iter()
        .filter(|finding| folded(finding))
        .map(key)
        .collect();
    let mut groups: Vec<(&str, Vec<&sc_core::Finding>)> = Vec::new();
    for finding in card
        .findings
        .iter()
        .filter(|finding| finding.engine != "a11y" && !folded(finding))
    {
        match groups.iter_mut().find(|(rule, _)| *rule == finding.rule) {
            Some((_, items)) => items.push(finding),
            None => groups.push((finding.rule.as_str(), vec![finding])),
        }
    }
    let errors = |items: &[&sc_core::Finding]| {
        items
            .iter()
            .filter(|finding| finding.severity == "error")
            .count()
    };
    groups.sort_by(|(a_rule, a), (b_rule, b)| {
        (errors(b) > 0)
            .cmp(&(errors(a) > 0))
            .then(a.len().cmp(&b.len()))
            .then(a_rule.cmp(b_rule))
    });
    for (rule, mut items) in groups {
        items.sort_by_key(|finding| finding.severity != "error");
        let errs = errors(&items);
        out.push_str("<details class=\"group\"");
        if errs > 0 && items.len() <= OPEN_LIMIT {
            out.push_str(" open");
        }
        out.push_str("><summary><code>");
        out.push_str(&esc(rule));
        out.push_str("</code> · ");
        out.push_str(&items.len().to_string());
        if errs > 0 {
            out.push_str(&format!(
                " <span class=\"pill fail\">{}</span>",
                plural(errs, "error", "errors")
            ));
        }
        if errs < items.len() {
            out.push_str(&format!(
                " <span class=\"pill warn\">{}</span>",
                plural(items.len() - errs, "warning", "warnings")
            ));
        }
        out.push_str("</summary>\n");
        for finding in items.iter().take(GROUP_LIMIT) {
            finding_card(out, finding, untested.contains(&key(finding)));
        }
        if items.len() > GROUP_LIMIT {
            out.push_str(&format!(
                "<p class=\"more\">{} more <code>{}</code> {} in the JSON and SARIF reports.</p>",
                items.len() - GROUP_LIMIT,
                esc(rule),
                if items.len() - GROUP_LIMIT == 1 {
                    "finding is"
                } else {
                    "findings are"
                }
            ));
        }
        out.push_str("</details>\n");
    }
    let a11y = card
        .findings
        .iter()
        .filter(|finding| finding.engine == "a11y")
        .count();
    if !untested.is_empty() {
        out.push_str(&format!(
            "<p class=\"more\">{} <code>complexity.untested</code> {} into the matching <code>crap.over_threshold</code> cards.</p>\n",
            untested.len(),
            if untested.len() == 1 { "finding is folded" } else { "findings are folded" }
        ));
    }
    if a11y > 0 {
        out.push_str(&format!(
            "<p class=\"more\">{} grouped under accessibility above.</p>\n",
            plural(
                a11y,
                "accessibility finding is",
                "accessibility findings are"
            )
        ));
    }
}

fn finding_card(out: &mut String, finding: &sc_core::Finding, untested: bool) {
    let cls = if finding.severity == "error" {
        "finding error"
    } else {
        "finding"
    };
    out.push_str("<div class=\"card ");
    out.push_str(cls);
    out.push_str("\"><h3>");
    out.push_str(&esc(&finding.id));
    out.push_str("</h3><div class=\"row\">");
    out.push_str("<span class=\"pill ");
    out.push_str(if finding.severity == "error" {
        "fail"
    } else {
        "warn"
    });
    out.push_str("\">");
    out.push_str(&esc(&finding.severity));
    out.push_str("</span><span class=\"pill info\">");
    out.push_str(&esc(&finding.rule));
    out.push_str("</span>");
    if !finding.disposition.is_empty() {
        out.push_str("<span class=\"pill dim\">");
        out.push_str(&esc(&finding.disposition));
        out.push_str("</span>");
    }
    out.push_str("<span class=\"pill dim\">");
    out.push_str(&esc(&finding.engine));
    out.push_str("</span></div><p>");
    out.push_str(&esc(&finding.message));
    out.push_str("</p>");
    let (functions, more) = evidence_functions(finding);
    if !functions.is_empty() {
        out.push_str("<ul class=\"fnlist\">");
        for (location, symbol) in &functions {
            out.push_str("<li><code>");
            out.push_str(&esc(location));
            out.push_str("</code> · <code>");
            out.push_str(&esc(symbol));
            out.push_str("</code></li>");
        }
        if more > 0 {
            out.push_str(&format!("<li class=\"more\">{more} more</li>"));
        }
        out.push_str("</ul>");
    }
    if let Some(log) = raw_log(finding) {
        out.push_str("<details class=\"log\"><summary>full output</summary><pre>");
        out.push_str(&esc(log));
        out.push_str("</pre></details>");
    }
    // Repo-level findings (file ".", no span or symbol) have no location.
    if finding.file != "." || finding.span.is_some() || finding.symbol.is_some() {
        out.push_str("<div style=\"font-size:12px;color:var(--dim)\">");
        out.push_str(&esc(&finding.file));
        if let Some(span) = &finding.span {
            out.push_str(&format!(":{}:{}", span.start_line, span.start_col));
        }
        if let Some(symbol) = &finding.symbol {
            out.push_str(" · <code>");
            out.push_str(&esc(symbol));
            out.push_str("</code>");
        }
        out.push_str("</div>");
    }
    if untested {
        out.push_str("<div class=\"suggest\">also <code>complexity.untested</code>: no coverage at this complexity</div>");
    }
    if let Some(action) = &finding.suggested_action {
        out.push_str("<div class=\"suggest\">suggested: ");
        out.push_str(&esc(action));
        out.push_str("</div>");
    }
    out.push_str("</div>\n");
}

fn llm_section(out: &mut String, card: &Scorecard) {
    let Some(section) = card.llm.as_ref() else {
        return;
    };
    out.push_str("<h2>llm</h2>\n<div class=\"card\">");
    if section.status == "skipped" {
        out.push_str("<p>skipped: ");
        out.push_str(&esc(section.reason.as_deref().unwrap_or("llm did not run")));
        out.push_str("</p></div>\n");
        return;
    }
    out.push_str("<p>");
    let mut wrote = false;
    if let Some(backend) = section.backend.as_deref() {
        out.push_str("backend <code>");
        out.push_str(&esc(backend));
        out.push_str("</code>");
        wrote = true;
    }
    if let Some(model) = section.model.as_deref() {
        if wrote {
            out.push_str(" · ");
        }
        out.push_str("model <code>");
        out.push_str(&esc(model));
        out.push_str("</code>");
        wrote = true;
    }
    if let Some(rounds) = section.rounds {
        if wrote {
            out.push_str(" · ");
        }
        out.push_str("rounds ");
        out.push_str(&rounds.to_string());
        wrote = true;
    }
    if let Some(verdict) = section.verdict.as_deref() {
        if wrote {
            out.push_str(" · ");
        }
        out.push_str("verdict <strong>");
        out.push_str(&esc(verdict));
        out.push_str("</strong>");
    }
    out.push_str("</p>");
    if !section.notes.is_empty() {
        out.push_str("<ul>");
        for note in section.notes.iter().take(10) {
            out.push_str("<li>");
            out.push_str(&esc(note));
            out.push_str("</li>");
        }
        out.push_str("</ul>");
    }
    out.push_str("</div>\n");
}

fn deep(out: &mut String, card: &Scorecard) {
    let m = &card.mutation;
    out.push_str("<h2>mutation · spec</h2>\n<div class=\"card\"><div class=\"row\" style=\"display:flex;gap:6px;flex-wrap:wrap\">");
    out.push_str("<span class=\"pill info\">");
    out.push_str(&esc(&m.status));
    out.push_str("</span>");
    if let Some(score) = m.score {
        out.push_str("<span class=\"pill dim\">score ");
        out.push_str(&format!("{score:.2}"));
        out.push_str("</span>");
    }
    out.push_str("<span class=\"pill dim\">killed ");
    out.push_str(&m.killed.to_string());
    out.push_str("</span><span class=\"pill dim\">survived ");
    out.push_str(&m.survived.to_string());
    out.push_str("</span><span class=\"pill dim\">timeout ");
    out.push_str(&m.timeout.to_string());
    out.push_str("</span></div>");
    match &card.spec.path {
        Some(path) => {
            out.push_str("<p style=\"font-size:12.5px\">spec <code>");
            out.push_str(&esc(path));
            out.push_str("</code> · gaps ");
            out.push_str(&card.spec.gaps.len().to_string());
            out.push_str("</p>");
            for gap in &card.spec.gaps {
                out.push_str("<div class=\"term\">");
                out.push_str(&esc(&gap.to_string()));
                out.push_str("</div>");
            }
        }
        None => out
            .push_str("<p style=\"font-size:12.5px;color:var(--dim)\">no spec file requested.</p>"),
    }
    out.push_str("</div>\n");
}

fn runs(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>runs</h2>\n<div class=\"card\"><table>");
    out.push_str("<tr><th>engine</th><th>command</th><th>exit</th><th>ms</th></tr>");
    for run in &card.runs {
        out.push_str("<tr><td><code>");
        out.push_str(&esc(&run.engine));
        out.push_str("</code></td><td class=\"cmd\"><div class=\"term\"><b>$ </b>");
        out.push_str(&esc(&run.command));
        out.push_str("</div></td><td>");
        match run.exit_code {
            Some(0) => out.push_str("<span class=\"pill pass\">0</span>"),
            Some(code) => out.push_str(&format!("<span class=\"pill fail\">{code}</span>")),
            None => out.push_str("<span class=\"pill dim\">—</span>"),
        }
        out.push_str("</td><td>");
        out.push_str(&run.duration_ms.to_string());
        out.push_str("</td></tr>");
    }
    out.push_str("</table></div>\n");
}

fn score_color(value: f64) -> &'static str {
    if value >= 0.9 {
        "#59e3a5"
    } else if value >= 0.7 {
        "#ffcf6e"
    } else {
        "#ff7a90"
    }
}

fn fmt_num(value: f64) -> String {
    if (value - value.round()).abs() < 1e-6 {
        format!("{}", value.round() as i64)
    } else {
        format!("{value:.1}")
    }
}

fn esc(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_core::{CrapFunction, CrapSection, Finding, Gate, LlmSection, Scorecard};

    #[test]
    fn html_matches_reviewed_golden() {
        let mut card = card();
        card.id = "golden-report".into();
        let actual = to_html(&card);
        let expected = include_str!("../../testdata/reports/card.html");
        if actual != expected {
            let mismatch = actual
                .bytes()
                .zip(expected.bytes())
                .position(|(actual, expected)| actual != expected)
                .unwrap_or_else(|| actual.len().min(expected.len()));
            panic!(
                "HTML differs from reviewed golden at byte {mismatch} (actual {} bytes, expected {} bytes)",
                actual.len(),
                expected.len()
            );
        }
    }

    #[test]
    fn html_says_why_llm_was_skipped_and_shows_notes_when_it_ran() {
        let mut card = card();
        let off = to_html(&card);
        assert!(!off.contains("<h2>llm</h2>"));
        card.llm = Some(LlmSection {
            status: "ran".into(),
            backend: Some("ollama".into()),
            model: Some("qwen2.5-coder".into()),
            rounds: None,
            verdict: None,
            notes: vec!["checked src/lib.rs against the intent".into()],
            reason: None,
        });
        let missing = to_html(&card);
        assert!(!missing.contains("no gaps"));
        assert!(!missing.contains("rounds"));
        card.llm = Some(LlmSection::ran(
            "ollama",
            "qwen2.5-coder",
            4,
            0,
            vec!["checked src/lib.rs against the intent".into()],
        ));
        card.engines_skipped.retain(|engine| engine != "llm");
        let ran = to_html(&card);
        assert!(ran.contains("no gaps"));
        assert!(ran.contains("checked src/lib.rs against the intent"));
        assert!(ran.contains("qwen2.5-coder"));
    }

    fn card() -> Scorecard {
        let mut card = Scorecard::skeleton("testdata/<good>&\"crate\"", 30);
        card.verdict = "fail".into();
        card.gates.push(Gate {
            id: "crap".into(),
            pass: false,
            enforced: true,
            reason: Some("1 function over threshold".into()),
        });
        card.crap = CrapSection {
            threshold: 30,
            worst: vec![CrapFunction {
                symbol: "classify".into(),
                file: "src/lib.rs".into(),
                cc: 11,
                coverage: 0.0,
                crap: 132.0,
            }],
        };
        card.findings.push(Finding {
            id: "crap:src/lib.rs:classify".into(),
            rule: "crap.over_threshold".into(),
            engine: "crap".into(),
            severity: "error".into(),
            file: "src/lib.rs".into(),
            span: None,
            symbol: Some("classify".into()),
            message: "CRAP 132 (CC=11, cov=0%) exceeds threshold 30".into(),
            evidence: serde_json::json!({}),
            suggested_action: Some("Add tests covering branches or split the function".into()),
            disposition: "fix".into(),
        });
        card
    }

    fn finding(rule: &str, engine: &str, severity: &str, file: &str, symbol: &str) -> Finding {
        Finding {
            id: format!("{engine}:{file}:{symbol}"),
            rule: rule.into(),
            engine: engine.into(),
            severity: severity.into(),
            file: file.into(),
            span: None,
            symbol: (!symbol.is_empty()).then(|| symbol.to_string()),
            message: format!("{rule} on {symbol}"),
            evidence: serde_json::json!({}),
            suggested_action: None,
            disposition: String::new(),
        }
    }

    #[test]
    fn html_groups_findings_by_rule_with_rare_errors_first() {
        let mut c = card();
        c.findings.push(finding(
            "crap.over_threshold",
            "crap",
            "error",
            "src/b.rs",
            "b",
        ));
        c.findings
            .push(finding("links.missing", "perf", "warning", "src/a.rs", "a"));
        c.findings.push(finding(
            "test.failed",
            "tests",
            "error",
            "src/lib.rs",
            "it_adds",
        ));
        let html = to_html(&c);
        let test = html.find("<summary><code>test.failed</code> · 1").unwrap();
        let crap = html
            .find("<summary><code>crap.over_threshold</code> · 2")
            .unwrap();
        let links = html
            .find("<summary><code>links.missing</code> · 1")
            .unwrap();
        assert!(test < crap && crap < links);
        assert!(html.contains("<details class=\"group\" open><summary><code>test.failed</code>"));
        assert!(html.contains("<details class=\"group\"><summary><code>links.missing</code>"));
        assert!(html.contains("<span class=\"pill fail\">2 errors</span>"));
    }

    #[test]
    fn html_collapses_big_error_groups_and_caps_cards() {
        let mut c = card();
        c.findings.clear();
        for i in 0..60 {
            let symbol = format!("f{i}");
            c.findings.push(finding(
                "crap.over_threshold",
                "crap",
                "error",
                "src/lib.rs",
                &symbol,
            ));
        }
        let html = to_html(&c);
        assert!(html
            .contains("<details class=\"group\"><summary><code>crap.over_threshold</code> · 60"));
        assert_eq!(
            html.matches("<div class=\"card finding error\">").count(),
            GROUP_LIMIT
        );
        assert!(html.contains(
            "10 more <code>crap.over_threshold</code> findings are in the JSON and SARIF reports."
        ));
    }

    #[test]
    fn html_folds_untested_into_the_matching_crap_card() {
        let mut c = card();
        c.findings.push(finding(
            "complexity.untested",
            "complexity",
            "error",
            "src/lib.rs",
            "classify",
        ));
        c.findings.push(finding(
            "complexity.untested",
            "complexity",
            "error",
            "src/lib.rs",
            "other",
        ));
        let html = to_html(&c);
        assert!(html.contains("also <code>complexity.untested</code>"));
        assert!(html.contains("<summary><code>complexity.untested</code> · 1"));
        assert!(html.contains("1 <code>complexity.untested</code> finding is folded"));
    }

    #[test]
    fn html_points_a11y_findings_to_their_section_and_drops_bare_dot() {
        let mut c = card();
        c.findings.push(finding(
            "a11y.img_alt",
            "a11y",
            "warning",
            "index.html",
            "img",
        ));
        c.findings
            .push(finding("coverage.missing", "coverage", "warning", ".", ""));
        let html = to_html(&c);
        assert!(!html.contains("<summary><code>a11y.img_alt</code>"));
        assert!(html.contains("1 accessibility finding is grouped under accessibility above."));
        assert!(!html.contains("<div style=\"font-size:12px;color:var(--dim)\">.</div>"));
    }

    #[test]
    fn html_says_coverage_not_measured_instead_of_zero() {
        let mut c = card();
        c.engines_run.retain(|engine| engine != "coverage");
        c.crap.worst.clear();
        let html = to_html(&c);
        assert!(html.contains("<b>—</b><span>coverage not measured</span>"));
        assert!(html.contains("nothing is treated as 0% coverage"));
        assert!(html.contains("No CRAP scores: coverage was not measured."));
        assert!(!html.contains("<span>coverage</span>"));
        assert!(html.contains("<span>crap max</span>"));
        assert!(html.contains("<span>over threshold</span>"));
    }

    #[test]
    fn html_keeps_measured_coverage_when_some_functions_lack_a_record() {
        let mut c = card();
        if !c.engines_run.iter().any(|engine| engine == "coverage") {
            c.engines_run.push("coverage".into());
        }
        c.gates[0].enforced = false;
        c.gates[0].pass = false;
        c.gates[0].reason =
            Some("some functions have no coverage record and were not scored".into());
        c.crap.worst[0].coverage = 0.4;
        c.metrics.coverage_changed = 0.4;
        let html = to_html(&c);
        assert!(html.contains("<b>40%</b><span>coverage</span>"));
        assert!(html.contains("<span class=\"cov\">40%</span>"));
        assert!(!html.contains("not measured"));
        assert!(!html.contains("CRAP is not scored"));
    }

    #[test]
    fn html_shows_measured_coverage_as_a_number() {
        let mut c = card();
        c.engines_run.push("coverage".into());
        c.crap.worst[0].coverage = 0.5;
        c.metrics.coverage_changed = 0.5;
        let html = to_html(&c);
        assert!(html.contains("<b>50%</b><span>coverage</span>"));
        assert!(html.contains("<span class=\"cov\">50%</span>"));
        assert!(!html.contains("not measured"));
    }

    #[test]
    fn html_tile_calls_sca_misses_undeclared_deps() {
        let mut measured = card();
        measured.metrics.undeclared_dependencies = 7;
        measured.metrics.hallucinated_imports = 0;
        let html = to_html(&measured);
        assert!(html.contains("<b>7</b><span>undeclared deps</span>"));
        assert!(!html.contains("hallucinated imports"));
        measured.metrics.hallucinated_imports = 1;
        let html = to_html(&measured);
        assert!(html.contains("<b>7</b><span>undeclared deps</span>"));
        assert!(html.contains("<b>1</b><span>hallucinated imports</span>"));
    }

    #[test]
    fn html_puts_the_raw_log_behind_a_disclosure() {
        let mut c = card();
        let mut lint = finding("lint.failed", "lint", "error", "src/lib.rs", "chunks_exact");
        lint.message = "error: using chunks_exact".into();
        lint.evidence = serde_json::json!({
            "command": "cargo clippy -- -D warnings",
            "diagnostic": "error: using chunks_exact",
            "log": "   Compiling demo v0.1.0\nerror: using chunks_exact <T>\n",
        });
        c.findings.push(lint);
        let html = to_html(&c);
        assert!(html.contains("<p>error: using chunks_exact</p><details class=\"log\"><summary>full output</summary><pre>   Compiling demo v0.1.0\nerror: using chunks_exact &lt;T&gt;</pre></details>"));
        // The CRAP card has no log, so exactly one disclosure.
        assert_eq!(html.matches("<details class=\"log\">").count(), 1);
    }

    #[test]
    fn html_rest_of_tree_names_paths_outside_the_diff() {
        let mut c = card();
        c.scope.mode = "diff".into();
        c.scope.paths = vec!["src/a.rs".into(), "src/b.rs".into()];
        c.scope.other_paths = Some(38);
        c.scope.base = Some("origin/develop".into());
        let html = to_html(&c);
        assert!(html.contains("2 paths in this diff; 38 other paths in the tree"));
        assert!(html.contains("diff · 2 paths; 38 other"));
        c.scope.mode = "tree".into();
        c.scope.other_paths = None;
        let html = to_html(&c);
        assert!(!html.contains("other paths in the tree"));
    }

    #[test]
    fn html_diff_scope_prints_the_diff_count_and_points_at_the_base() {
        let mut c = card();
        c.scope.mode = "diff".into();
        c.scope.base = Some("origin/main".into());
        c.metrics.crap_over_threshold = 4;
        let html = to_html(&c);
        assert!(html.contains("diff scope: 4 functions over threshold in this diff. The tree-wide count is on the latest push run of main."));
        c.scope.base = Some("HEAD~1".into());
        c.metrics.crap_over_threshold = 1;
        let html = to_html(&c);
        assert!(html.contains("diff scope: 1 function over threshold in this diff. The tree-wide count is on a tree-scope run (sc analyze without --diff)."));
        c.scope.mode = "tree".into();
        assert!(!to_html(&c).contains("diff scope:"));
    }

    #[test]
    fn html_lists_evidence_functions_with_the_real_total() {
        let mut c = card();
        let mut unmatched = finding("coverage.unmatched", "coverage", "warning", ".", "");
        unmatched.evidence = serde_json::json!({
            "unmatched": 25,
            "functions": [
                {"file": "src/a.rs", "symbol": "a::run", "line": 12},
                {"file": "src/b.rs", "symbol": "b<T>::go", "span": {"start_line": 3}},
                {"file": "src/c.rs", "symbol": "c::plain"},
            ],
        });
        c.findings.push(unmatched);
        let html = to_html(&c);
        assert!(html.contains("<ul class=\"fnlist\"><li><code>src/a.rs:12</code> · <code>a::run</code></li><li><code>src/b.rs:3</code> · <code>b&lt;T&gt;::go</code></li><li><code>src/c.rs</code> · <code>c::plain</code></li><li class=\"more\">22 more</li></ul>"));
    }

    #[test]
    fn html_skips_the_list_when_the_finding_names_its_one_function() {
        let mut c = card();
        let mut one = finding(
            "coverage.unmatched",
            "coverage",
            "warning",
            "src/a.rs",
            "a::run",
        );
        one.evidence = serde_json::json!({
            "unmatched": 1,
            "functions": [{"file": "src/a.rs", "symbol": "a::run", "line": 12}],
        });
        c.findings.push(one);
        assert!(!to_html(&c).contains("class=\"fnlist\""));
    }

    #[test]
    fn html_renders_verdict_and_sections() {
        let html = to_html(&card());
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("FAIL"));
        assert!(html.contains("classify"));
        assert!(html.contains("crap.over_threshold"));
        assert!(html.contains("worst crap"));
        assert!(html.contains("runs"));
    }

    #[test]
    fn html_escapes_untrusted_text_and_stays_offline() {
        let html = to_html(&card());
        assert!(html.contains("testdata/&lt;good&gt;&amp;&quot;crate&quot;"));
        assert!(!html.contains("<good>"));
        for marker in ["unpkg", "cdn.", "http://", "https://"] {
            assert!(!html.contains(marker), "report must not fetch {marker}");
        }
    }

    #[test]
    fn html_collapses_tree_paths_behind_details() {
        let mut c = card();
        c.scope.mode = "tree".into();
        c.scope.paths = (0..12).map(|i| format!("src/module/file{i}.rs")).collect();
        let html = to_html(&c);
        assert!(html.contains("12 paths <details>"));
        assert!(html.contains("/<wbr>"));
        assert!(!html.contains("file0.rs, src/module/file1.rs"));
    }

    #[test]
    fn html_keeps_short_diff_paths_inline() {
        let mut c = card();
        c.scope.mode = "diff".into();
        c.scope.paths = vec!["src/a.rs".into(), "src/b.rs".into()];
        let html = to_html(&c);
        assert!(!html.contains("<details>"));
        assert!(html.contains("src/a.rs, src/b.rs"));
    }

    #[test]
    fn html_marks_pass_with_failures_report_only() {
        // A report-only run must not read as a clean pass.
        let mut c = card();
        c.verdict = "pass".into();
        c.gates[0].enforced = false;
        let html = to_html(&c);
        assert!(html.contains("<span class=\"verdict report\">REPORT ONLY</span>"));
        assert!(html.contains("1 failing gate, none enforced"));
        assert!(!html.contains("verdict pass"));
        // The flow strip and page title agree with the badge.
        assert!(html.contains("<div class=\"step\"><b>verdict</b><span>report only</span>"));
        assert!(html.contains("— report only</title>"));
    }

    #[test]
    fn html_fails_when_an_enforced_gate_fails_even_if_verdict_says_pass() {
        let mut c = card();
        c.verdict = "pass".into();
        c.gates[0].pass = false;
        c.gates[0].enforced = true;
        let html = to_html(&c);
        assert!(html.contains("<span class=\"verdict fail\">FAIL</span>"));
        assert!(!html.contains("REPORT ONLY"));
    }

    #[test]
    fn html_advisory_miss_stays_pass_with_a_note() {
        // Enforced gates passed; only advisory sca failed.
        let mut c = card();
        c.verdict = "pass".into();
        c.gates[0].pass = true;
        c.gates.push(Gate {
            id: "sca".into(),
            pass: false,
            enforced: false,
            reason: Some("3 undeclared dependencies".into()),
        });
        let html = to_html(&c);
        assert!(html.contains("<span class=\"verdict pass\">PASS</span>"));
        assert!(html.contains("1 advisory gate failing"));
        assert!(!html.contains("REPORT ONLY"));
        assert!(html.contains("<div class=\"step hi\"><b>verdict</b><span>pass</span>"));
    }

    #[test]
    fn html_flow_scope_counts_paths_not_skips() {
        let mut c = card();
        c.scope.paths = vec!["src/a.rs".into(), "src/b.rs".into()];
        let html = to_html(&c);
        assert!(html.contains("<b>scope</b><span>tree · 2 paths</span>"));
        assert!(!html.contains("2 skipped"));
    }

    #[test]
    fn html_clean_pass_stays_green() {
        let mut c = card();
        c.verdict = "pass".into();
        c.gates[0].pass = true;
        c.gates[0].reason = None;
        let html = to_html(&c);
        assert!(html.contains("<span class=\"verdict pass\">PASS</span>"));
        assert!(!html.contains("REPORT ONLY"));
    }

    #[test]
    fn html_truncates_long_sha_with_full_sha_on_hover() {
        let mut c = card();
        let full = "0123456789abcdef0123456789abcdef01234567";
        c.git.head = Some(full.into());
        c.git.dirty = true;
        let html = to_html(&c);
        // Full SHA plus state must not appear as flat text (it overflowed
        // the header column); short SHA shows, full SHA rides in title.
        assert!(!html.contains(&format!("{full} (dirty)")));
        assert!(html.contains(&format!("title=\"{full}\"")));
        assert!(html.contains(&full[..12]));
        // A long value stays inside its cell. The old 180px minimum let the
        // SHA paint across the tests column.
        assert!(html.contains("minmax(min(100%,220px),1fr)"));
        assert!(html.contains(".meta>div{min-width:0;overflow:hidden}"));
    }

    #[test]
    fn html_fits_the_viewport() {
        let html = to_html(&card());
        // The report spans the window instead of a fixed 880px column.
        assert!(!html.contains("max-width:880px"));
        assert!(html.contains("main{padding:28px clamp(12px,3vw,40px) 60px}"));
        // An absolute repo path or run id wraps instead of widening the page.
        assert!(html.contains(".hero>div{flex:1 1 220px;min-width:0;overflow-wrap:anywhere}"));
        // A table too wide for a phone scrolls inside its card.
        assert!(html.contains(".card:has(>table){overflow-x:auto}"));
    }

    #[test]
    fn html_renders_unprovided_gates_as_skipped_outside_ratio() {
        let mut c = card();
        c.gates.push(Gate {
            id: "sca".into(),
            pass: false,
            enforced: false,
            reason: Some("not provided by this pack".into()),
        });
        let html = to_html(&c);
        assert!(html.contains("<span class=\"pill dim\">skipped</span>"));
        // crap fails, sca is not provided: the flow ratio counts provided
        // gates only instead of "1/3 pass".
        assert!(html.contains("0/1 pass"));
        assert!(!html.contains("/2 pass"));
    }
}
