// SPDX-License-Identifier: MPL-2.0
//! Self-contained HTML scorecard report.
//!
//! `to_html` renders one `.html` file with inline CSS and JS and no external
//! requests, so it works from `file://` and from any static server. The page
//! reads top to bottom: verdict and gates, health, findings grouped by file
//! and rule (with filters and search), worst CRAP, then run details. Every
//! long string wraps or is middle-elided with the full value in `title` and
//! the copy button, so no viewport width scrolls sideways. Numbers sc did not
//! measure read "not measured".

use sc_core::{Finding, Scorecard};

use crate::format::fmt_num;

const CSS: &str = include_str!("report.css");
const JS: &str = include_str!("report.js");

pub fn to_html(card: &Scorecard) -> String {
    let view = View::of(card);
    let mut out = String::new();
    out.push_str(
        "<!DOCTYPE html>\n<html lang=\"en\" class=\"no-js\">\n<head>\n<meta charset=\"utf-8\">\n",
    );
    out.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    out.push_str("<meta name=\"color-scheme\" content=\"light dark\">\n<title>");
    out.push_str(&esc(&format!(
        "scorecard: {} — {}",
        card.repo,
        Outcome::of(card).word(card)
    )));
    out.push_str("</title>\n<style>\n");
    out.push_str(CSS);
    out.push_str(
        "</style>\n</head>\n<body>\n<a class=\"skip\" href=\"#findings\">Skip to findings</a>\n",
    );
    header(&mut out, card);
    out.push_str("<main>\n");
    summary(&mut out, card, &view);
    flow(&mut out, card);
    health(&mut out, card);
    findings(&mut out, &view);
    crap(&mut out, card);
    run_details(&mut out, card);
    out.push_str(
        "</main>\n<footer><p>Generated by <code>sc analyze --format html</code>. Scorecard ",
    );
    out.push_str(&esc(&card.id));
    out.push_str(", schema ");
    out.push_str(&esc(&card.version));
    out.push_str(". This page makes no network requests.</p></footer>\n<script>\n");
    out.push_str(JS);
    out.push_str("</script>\n</body>\n</html>\n");
    out
}

/// How a verdict should read, shared by every renderer. Exit code and the
/// verdict field are untouched; this only picks the words.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Outcome {
    Fail,
    /// Every provided gate passed.
    Pass,
    /// Enforced gates passed; this many advisory gates (such as `sca`) failed.
    Advisory(usize),
    /// No gate was enforced (empty `--fail-on`) and this many failed. Must
    /// never read as a clean pass.
    ReportOnly(usize),
}

impl Outcome {
    pub(crate) fn of(card: &Scorecard) -> Self {
        if card.verdict != "pass" {
            return Outcome::Fail;
        }
        let provided: Vec<_> = card.gates.iter().filter(|gate| provided(gate)).collect();
        let failing = provided.iter().filter(|gate| !gate.pass).count();
        if failing == 0 {
            Outcome::Pass
        } else if provided.iter().any(|gate| gate.enforced) {
            Outcome::Advisory(failing)
        } else {
            Outcome::ReportOnly(failing)
        }
    }

    /// "1 failing gate, none enforced" or "1 advisory gate failing".
    pub(crate) fn note(self) -> Option<String> {
        let noun = |n: usize| if n == 1 { "gate" } else { "gates" };
        match self {
            Outcome::ReportOnly(n) => Some(format!("{n} failing {}, none enforced", noun(n))),
            Outcome::Advisory(n) => Some(format!("{n} advisory {} failing", noun(n))),
            Outcome::Fail | Outcome::Pass => None,
        }
    }

    /// Verdict word for the page title and the flow strip.
    fn word(self, card: &Scorecard) -> &str {
        match self {
            Outcome::ReportOnly(_) => "report only",
            _ => &card.verdict,
        }
    }
}

/// Reason marker for gates the active pack does not evaluate. Such gates
/// carry no signal: they render as skipped and stay out of the pass ratio.
pub(crate) const NOT_PROVIDED: &str = "not provided by this pack";

fn provided(gate: &sc_core::Gate) -> bool {
    gate.reason.as_deref() != Some(NOT_PROVIDED)
}

fn header(out: &mut String, card: &Scorecard) {
    out.push_str("<header class=\"top\"><div class=\"brand\"><span class=\"logo\" aria-hidden=\"true\">sc</span>scorecard</div><div class=\"repo\">");
    out.push_str(&esc(&card.repo));
    out.push_str("</div><dl class=\"facts\">");
    fact(out, "pack", &esc(&card.pack));
    fact(out, "scope", &esc(&card.scope.mode));
    fact(out, "git", &git(card));
    fact(out, "tests", &esc(&card.test_selection));
    out.push_str("</dl></header>\n");
}

fn fact(out: &mut String, label: &str, value_html: &str) {
    out.push_str("<div><dt>");
    out.push_str(label);
    out.push_str("</dt><dd>");
    out.push_str(value_html);
    out.push_str("</dd></div>");
}

/// Short SHA with the full one on hover, plus clean or dirty.
fn git(card: &Scorecard) -> String {
    let state = if card.git.dirty { "dirty" } else { "clean" };
    match card.git.head.as_deref().filter(|head| !head.is_empty()) {
        Some(head) => {
            let short: String = head.chars().take(12).collect();
            format!(
                "<code title=\"{}\">{}</code> {state}",
                esc(head),
                esc(&short)
            )
        }
        None => format!("none, {state}"),
    }
}

fn summary(out: &mut String, card: &Scorecard, view: &View) {
    let outcome = Outcome::of(card);
    let (cls, icon, label) = match outcome {
        Outcome::Fail => ("v-fail", "✕", "FAIL"),
        Outcome::ReportOnly(_) => ("v-report", "◐", "REPORT ONLY"),
        Outcome::Pass | Outcome::Advisory(_) => ("v-pass", "✓", "PASS"),
    };
    out.push_str(
        "<section class=\"summary\" aria-labelledby=\"verdict-h\"><div class=\"card verdict ",
    );
    out.push_str(cls);
    out.push_str(&format!(
        "\"><h1 id=\"verdict-h\" class=\"badge\"><span aria-hidden=\"true\">{icon}</span>{label}</h1><p class=\"because\">"
    ));
    out.push_str(&esc(&verdict_sentence(card, outcome)));
    out.push_str("</p><ul class=\"counts\">");
    for (sev, count) in &view.severities {
        out.push_str(&format!(
            "<li class=\"c-{sev}\"><b>{count}</b> {}</li>",
            if *count == 1 {
                sev.to_string()
            } else {
                format!("{sev}s")
            }
        ));
    }
    out.push_str(&format!(
        "<li><b>{}</b> {}</li></ul></div>",
        view.files.len(),
        if view.files.len() == 1 {
            "file"
        } else {
            "files"
        }
    ));
    gates(out, card);
    out.push_str("</section>\n");
}

/// One sentence that says why the verdict is what it is.
fn verdict_sentence(card: &Scorecard, outcome: Outcome) -> String {
    let failing = |enforced: Option<bool>| -> Vec<&str> {
        card.gates
            .iter()
            .filter(|gate| provided(gate) && !gate.pass)
            .filter(|gate| enforced.is_none_or(|e| gate.enforced == e))
            .map(|gate| gate.id.as_str())
            .collect()
    };
    let list = |ids: Vec<&str>| {
        format!(
            "{} ({})",
            plural(ids.len(), "gate", "gates"),
            ids.join(", ")
        )
    };
    match outcome {
        Outcome::Fail if failing(Some(true)).is_empty() => {
            "The analyzer could not finish. The findings below say what stopped it.".into()
        }
        Outcome::Fail => format!("{} failed.", list(failing(Some(true)))),
        Outcome::Pass => "Every gate that ran passed.".into(),
        Outcome::Advisory(_) => format!(
            "Enforced gates passed. {} advisory and failing.",
            list(failing(None))
        ),
        Outcome::ReportOnly(_) => format!(
            "No gate is enforced in this run, so it passes. {} would fail if enforced.",
            list(failing(None))
        ),
    }
}

fn gates(out: &mut String, card: &Scorecard) {
    out.push_str("<div class=\"card\"><h2>Gates</h2><ul class=\"gates\">");
    for gate in &card.gates {
        let (st, mark, kind) = if !provided(gate) {
            ("st-skip", "–", "skipped")
        } else if gate.enforced {
            (
                if gate.pass { "st-pass" } else { "st-fail" },
                if gate.pass { "✓" } else { "✕" },
                "enforced",
            )
        } else {
            (
                if gate.pass { "st-pass" } else { "st-fail" },
                if gate.pass { "✓" } else { "✕" },
                "reported only",
            )
        };
        let result = if !provided(gate) {
            "skipped"
        } else if gate.pass {
            "pass"
        } else {
            "fail"
        };
        out.push_str(&format!(
            "<li><span class=\"st {st}\" aria-hidden=\"true\">{mark}</span><code>{}</code><span class=\"tag{}\">{kind}</span><span class=\"sr-only\">{result}</span>",
            esc(&gate.id),
            if kind == "enforced" { " enf" } else { "" }
        ));
        if let Some(reason) = gate
            .reason
            .as_deref()
            .filter(|r| provided(gate) && !r.is_empty())
        {
            out.push_str("<span class=\"reason\">");
            out.push_str(&esc(reason));
            out.push_str("</span>");
        }
        out.push_str("</li>");
    }
    out.push_str("</ul></div>");
}

fn flow(out: &mut String, card: &Scorecard) {
    let provided: Vec<_> = card.gates.iter().filter(|gate| provided(gate)).collect();
    let passed = provided.iter().filter(|gate| gate.pass).count();
    let ratio = if provided.is_empty() {
        "n/a".to_string()
    } else {
        format!("{passed}/{} pass", provided.len())
    };
    let scope = match card.scope.paths.len() {
        0 => card.scope.mode.clone(),
        n => format!("{} · {}", card.scope.mode, plural(n, "path", "paths")),
    };
    let engines = match card.engines_skipped.len() {
        0 => format!("{} run", card.engines_run.len()),
        n => format!("{} run · {n} skipped", card.engines_run.len()),
    };
    let outcome = Outcome::of(card);
    out.push_str("<ol class=\"flow\" aria-label=\"How this verdict was reached\">");
    for (title, main, hi) in [
        ("scope", scope.as_str(), false),
        ("pack", card.pack.as_str(), false),
        ("engines", engines.as_str(), false),
        ("gates", ratio.as_str(), true),
        (
            "verdict",
            outcome.word(card),
            matches!(outcome, Outcome::Pass | Outcome::Advisory(_)),
        ),
    ] {
        out.push_str(&format!(
            "<li><div class=\"step{}\"><b>{title}</b><span>{}</span></div></li>",
            if hi { " hi" } else { "" },
            esc(main)
        ));
    }
    out.push_str("</ol>\n");
}

/// Engines behind each score. A score whose engines all stayed off was not
/// measured; its 1.00 default must not read as a result.
const SCORE_ENGINES: [(&str, &[&str]); 5] = [
    ("correctness", &["compile", "tests", "lint", "html"]),
    ("efficiency", &["perf"]),
    ("maintainability", &["complexity", "crap", "coverage"]),
    ("security", &["secrets", "sca"]),
    ("a11y", &["a11y"]),
];

fn ran(card: &Scorecard, engines: &[&str]) -> bool {
    card.engines_run
        .iter()
        .any(|engine| engines.contains(&engine.as_str()))
}

fn health(out: &mut String, card: &Scorecard) {
    let s = &card.scores;
    let values = [
        s.correctness,
        s.efficiency,
        s.maintainability,
        s.security,
        s.a11y,
    ];
    out.push_str("<section aria-labelledby=\"health-h\"><h2 id=\"health-h\">Health</h2><div class=\"health\"><div class=\"card\"><ul class=\"scores\">");
    for ((name, engines), value) in SCORE_ENGINES.iter().zip(values) {
        out.push_str(&format!("<li><span>{name}</span>"));
        if ran(card, engines) {
            let pct = (value.clamp(0.0, 1.0) * 100.0).round() as i64;
            out.push_str(&format!(
                "<span class=\"bar\" aria-hidden=\"true\"><i class=\"{}\" style=\"width:{pct}%\"></i></span><span class=\"sval\">{value:.2}</span></li>",
                level(value)
            ));
        } else {
            out.push_str(&format!(
                "<span class=\"bar\" aria-hidden=\"true\"></span><span class=\"sval nm\" title=\"{} did not run\">not measured</span></li>",
                engines.join(", ")
            ));
        }
    }
    out.push_str("</ul></div><div class=\"card\"><ul class=\"tiles\">");
    let m = &card.metrics;
    tile(out, Some(m.loc_changed.to_string()), "lines changed");
    tile(out, Some(m.files_changed.to_string()), "files changed");
    tile(
        out,
        coverage_measured(card).then(|| format!("{:.0}%", m.coverage_changed * 100.0)),
        "coverage",
    );
    let crapped = ran(card, &["crap"]);
    tile(out, crapped.then(|| fmt_num(m.crap_max)), "CRAP max");
    tile(
        out,
        crapped.then(|| m.crap_over_threshold.to_string()),
        "over CRAP threshold",
    );
    tile(
        out,
        ran(card, &["sca"]).then(|| m.hallucinated_imports.to_string()),
        "undeclared deps",
    );
    out.push_str("</ul></div></div></section>\n");
}

fn level(value: f64) -> &'static str {
    if value >= 0.9 {
        "lvl-ok"
    } else if value >= 0.7 {
        "lvl-warn"
    } else {
        "lvl-bad"
    }
}

fn tile(out: &mut String, value: Option<String>, label: &str) {
    match value {
        Some(value) => out.push_str(&format!(
            "<li><b>{}</b><span>{label}</span></li>",
            esc(&value)
        )),
        None => out.push_str(&format!(
            "<li><b class=\"nm\">not measured</b><span>{label}</span></li>"
        )),
    }
}

/// Coverage counts as measured only when the coverage engine ran. Otherwise
/// every CRAP number assumes 0% coverage, and 0% must not read as a result.
pub(crate) fn coverage_measured(card: &Scorecard) -> bool {
    card.engines_run.iter().any(|engine| engine == "coverage")
}

/// One sentence for every renderer when coverage was not measured.
pub(crate) const COVERAGE_NOT_MEASURED: &str =
    "Coverage was not measured, so CRAP assumes 0% coverage. These numbers are an upper bound.";
/// A diff run only scores changed functions, so it has no tree-wide CRAP
/// count. Say what the number covers and where the tree total lives
/// rather than inventing one. `None` outside diff scope.
pub(crate) fn diff_baseline(card: &Scorecard) -> Option<String> {
    if card.scope.mode != "diff" {
        return None;
    }
    let tree = match base_branch(card) {
        Some(branch) => format!("the latest push run of {branch}"),
        None => "a tree-scope run (sc analyze without --diff)".into(),
    };
    Some(format!(
        "diff scope: {} over threshold in this diff. The tree-wide count is on {tree}.",
        plural(
            card.metrics.crap_over_threshold as usize,
            "function",
            "functions"
        )
    ))
}

/// Short terminal form of `diff_baseline`; fits 80 columns.
pub(crate) fn diff_baseline_short(card: &Scorecard) -> Option<String> {
    if card.scope.mode != "diff" {
        return None;
    }
    let tree = match base_branch(card) {
        Some(branch) => format!("latest {branch} push run"),
        None => "a run without --diff".into(),
    };
    Some(format!(
        "diff scope: {} over threshold here; tree count: {tree}",
        card.metrics.crap_over_threshold
    ))
}

/// The branch a diff was taken against (`origin/main` reads as `main`).
/// `None` for a commit-ish base such as HEAD~1 or a SHA, which has no push
/// run of its own to point at.
fn base_branch(card: &Scorecard) -> Option<&str> {
    let base = card.scope.base.as_deref()?;
    let branch = base.strip_prefix("origin/").unwrap_or(base);
    let commitish = branch.is_empty()
        || branch.starts_with("HEAD")
        || branch.contains(['~', '^'])
        || (branch.len() >= 7 && branch.chars().all(|c| c.is_ascii_hexdigit()));
    (!commitish).then_some(branch)
}

/// Findings arranged for the page: grouped by file, then by rule, with
/// repeated messages collapsed into one row. `complexity.untested` repeats
/// `crap.over_threshold` for the same function, so it folds into that row.
struct View<'a> {
    files: Vec<FileGroup<'a>>,
    /// (severity, count) in error, warning, info order, present ones only.
    severities: Vec<(&'static str, usize)>,
    engines: Vec<(&'a str, usize)>,
    rules: Vec<(&'a str, usize)>,
    total: usize,
    folded: usize,
}

struct FileGroup<'a> {
    path: String,
    rules: Vec<RuleGroup<'a>>,
}

struct RuleGroup<'a> {
    rule: &'a str,
    rows: Vec<Row<'a>>,
}

/// One message in one file under one rule; `lines` holds every occurrence.
struct Row<'a> {
    finding: &'a Finding,
    lines: Vec<u32>,
    count: usize,
    untested: bool,
}

/// Rows shown per rule group in one file. The rest stay in the JSON and
/// SARIF reports, so a thousand-finding tree stays a readable page.
const GROUP_LIMIT: usize = 50;

/// File groups at or under this many findings start open when they hold an
/// error. Without script, a closed group still shows its counts.
const OPEN_LIMIT: usize = 10;

fn severity(finding: &Finding) -> &'static str {
    match finding.severity.as_str() {
        "error" => "error",
        "warning" => "warning",
        _ => "info",
    }
}

fn line_of(finding: &Finding) -> Option<u32> {
    finding.span.as_ref().map(|span| span.start_line)
}

impl<'a> View<'a> {
    fn of(card: &'a Scorecard) -> Self {
        let key = |f: &Finding| (f.file.clone(), f.symbol.clone());
        let crap_keys: Vec<_> = card
            .findings
            .iter()
            .filter(|f| f.rule == "crap.over_threshold")
            .map(key)
            .collect();
        let is_folded = |f: &Finding| {
            f.rule == "complexity.untested" && f.symbol.is_some() && crap_keys.contains(&key(f))
        };
        let untested: Vec<_> = card
            .findings
            .iter()
            .filter(|f| is_folded(f))
            .map(key)
            .collect();
        let mut view = View {
            files: Vec::new(),
            severities: Vec::new(),
            engines: Vec::new(),
            rules: Vec::new(),
            total: 0,
            folded: untested.len(),
        };
        for finding in card.findings.iter().filter(|f| !is_folded(f)) {
            view.add(finding, &card.repo, untested.contains(&key(finding)));
        }
        view.sort();
        view
    }

    fn add(&mut self, finding: &'a Finding, repo: &str, untested: bool) {
        self.total += 1;
        bump(&mut self.engines, finding.engine.as_str());
        bump(&mut self.rules, finding.rule.as_str());
        let path = rel_path(&finding.file, repo);
        let file = match self.files.iter().position(|g| g.path == path) {
            Some(i) => &mut self.files[i],
            None => {
                self.files.push(FileGroup {
                    path,
                    rules: Vec::new(),
                });
                self.files.last_mut().expect("just pushed")
            }
        };
        let group = match file.rules.iter().position(|g| g.rule == finding.rule) {
            Some(i) => &mut file.rules[i],
            None => {
                file.rules.push(RuleGroup {
                    rule: &finding.rule,
                    rows: Vec::new(),
                });
                file.rules.last_mut().expect("just pushed")
            }
        };
        match group
            .rows
            .iter_mut()
            .find(|row| row.finding.message == finding.message)
        {
            Some(row) => {
                row.count += 1;
                row.lines.extend(line_of(finding));
            }
            None => group.rows.push(Row {
                finding,
                lines: line_of(finding).into_iter().collect(),
                count: 1,
                untested,
            }),
        }
    }

    /// Repo-level findings first (they say why engines were skipped), then
    /// files with the most errors. Inside a file, rules holding errors come
    /// first and smallest first, since a rare error is usually the one to act on.
    fn sort(&mut self) {
        for sev in ["error", "warning", "info"] {
            let n = self.files.iter().map(|f| f.count(sev)).sum();
            if n > 0 {
                self.severities.push((sev, n));
            }
        }
        for file in &mut self.files {
            for group in &mut file.rules {
                for row in &mut group.rows {
                    row.lines.sort_unstable();
                }
                group.rows.sort_by_key(|row| {
                    (severity(row.finding) != "error", row.lines.first().copied())
                });
            }
            file.rules.sort_by(|a, b| {
                (b.count("error") > 0)
                    .cmp(&(a.count("error") > 0))
                    .then(a.total().cmp(&b.total()))
                    .then(a.rule.cmp(b.rule))
            });
        }
        self.files.sort_by(|a, b| {
            (b.path == REPO_LEVEL)
                .cmp(&(a.path == REPO_LEVEL))
                .then(b.count("error").cmp(&a.count("error")))
                .then(b.total().cmp(&a.total()))
                .then(a.path.cmp(&b.path))
        });
        self.engines.sort();
        self.rules.sort();
    }
}

impl FileGroup<'_> {
    fn count(&self, sev: &str) -> usize {
        self.rules.iter().map(|g| g.count(sev)).sum()
    }

    fn total(&self) -> usize {
        self.rules.iter().map(RuleGroup::total).sum()
    }
}

impl RuleGroup<'_> {
    fn count(&self, sev: &str) -> usize {
        self.rows
            .iter()
            .filter(|row| severity(row.finding) == sev)
            .map(|row| row.count)
            .sum()
    }

    fn total(&self) -> usize {
        self.rows.iter().map(|row| row.count).sum()
    }
}

fn bump<'a>(counts: &mut Vec<(&'a str, usize)>, key: &'a str) {
    match counts.iter_mut().find(|(k, _)| *k == key) {
        Some((_, n)) => *n += 1,
        None => counts.push((key, 1)),
    }
}

/// Label for findings that belong to the repository rather than a file.
const REPO_LEVEL: &str = "(repository)";

/// Paths relative to the analyzed repo; repo-level findings (".") get a label.
fn rel_path(file: &str, repo: &str) -> String {
    let file = file.strip_prefix("./").unwrap_or(file);
    let repo = repo.trim_end_matches('/');
    if file.is_empty() || file == "." {
        return REPO_LEVEL.into();
    }
    match file
        .strip_prefix(repo)
        .and_then(|rest| rest.strip_prefix('/'))
    {
        Some(rest) if repo != "." && !rest.is_empty() => rest.to_string(),
        _ => file.to_string(),
    }
}

/// A path that elides its directories first, then its file name, with the
/// full text in `title`.
fn path_html(path: &str, line: Option<u32>) -> String {
    let full = match line {
        Some(line) => format!("{path}:{line}"),
        None => path.to_string(),
    };
    let split = path.rfind('/').map_or(0, |i| i + 1);
    let (head, tail) = full.split_at(split);
    let head = if head.is_empty() {
        String::new()
    } else {
        format!("<span class=\"ph\">{}</span>", esc(head))
    };
    format!(
        "<span class=\"path\" title=\"{}\">{head}<span class=\"pt\">{}</span></span>",
        esc(&full),
        esc(tail)
    )
}

fn findings(out: &mut String, view: &View) {
    out.push_str("<section id=\"findings\" aria-labelledby=\"findings-h\"><div class=\"sec-head\"><h2 id=\"findings-h\">Findings <span class=\"n\">");
    out.push_str(&view.total.to_string());
    out.push_str("</span></h2>");
    if view.total == 0 {
        out.push_str("</div><p class=\"card empty\">No findings. Every engine that ran came back clean.</p></section>\n");
        return;
    }
    out.push_str(&format!(
        "<p id=\"shown\" class=\"shown\" aria-live=\"polite\">{} in {}</p></div><div class=\"fx\">",
        plural(view.total, "finding", "findings"),
        plural(view.files.len(), "file", "files")
    ));
    filters(out, view);
    out.push_str("<div class=\"groups\">");
    let mut anchors = Vec::new();
    for file in &view.files {
        file_group(out, file, &mut anchors);
    }
    if view.folded > 0 {
        out.push_str(&format!(
            "<p class=\"note\">{} into the matching <code>crap.over_threshold</code> rows.</p>",
            plural(
                view.folded,
                "complexity.untested finding is folded",
                "complexity.untested findings are folded"
            )
        ));
    }
    out.push_str("</div></div></section>\n");
}

fn filters(out: &mut String, view: &View) {
    out.push_str("<aside class=\"card filters js-only\" aria-label=\"Filter findings\"><div class=\"search\"><label for=\"q\">Search</label><input id=\"q\" type=\"search\" placeholder=\"path, rule, symbol or text\" autocomplete=\"off\" spellcheck=\"false\"></div>");
    let severities: Vec<(&str, usize)> = view.severities.iter().map(|(s, n)| (*s, *n)).collect();
    facet(out, "Severity", "sev", &severities);
    facet(out, "Engine", "eng", &view.engines);
    facet(out, "Rule", "rule", &view.rules);
    out.push_str("<div class=\"btns\"><button type=\"button\" data-act=\"expand\">Expand all</button><button type=\"button\" data-act=\"collapse\">Collapse all</button></div></aside>");
}

fn facet(out: &mut String, legend: &str, name: &str, counts: &[(&str, usize)]) {
    out.push_str(&format!(
        "<fieldset><legend>{legend}</legend><div class=\"facet\">"
    ));
    for (i, (value, n)) in counts.iter().enumerate() {
        out.push_str(&format!(
            "<div class=\"opt\"><input type=\"checkbox\" id=\"fc-{name}-{i}\" name=\"{name}\" value=\"{v}\" checked><label for=\"fc-{name}-{i}\"><span>{v}</span><span class=\"n\">{n}</span></label></div>",
            v = esc(value)
        ));
    }
    out.push_str("</div></fieldset>");
}

fn file_group(out: &mut String, file: &FileGroup, anchors: &mut Vec<String>) {
    let errors = file.count("error");
    let open = errors > 0 && file.total() <= OPEN_LIMIT;
    out.push_str(&format!(
        "<details class=\"fg\"{}><summary><span class=\"fg-name\">",
        if open { " open" } else { "" }
    ));
    out.push_str(&path_html(&file.path, None));
    out.push_str("</span><span class=\"pills\">");
    for sev in ["error", "warning", "info"] {
        let n = file.count(sev);
        if n > 0 {
            out.push_str(&format!(
                "<span class=\"pill p-{sev}\">{}</span>",
                plural(n, sev, &format!("{sev}s"))
            ));
        }
    }
    out.push_str("</span></summary><div class=\"gbody\">");
    for group in &file.rules {
        out.push_str(&format!(
            "<div class=\"rg\"><h3 class=\"rh\"><code>{}</code><span>{}</span></h3>",
            esc(group.rule),
            group.total()
        ));
        for row in group.rows.iter().take(GROUP_LIMIT) {
            finding_row(out, row, &file.path, anchors);
        }
        if group.rows.len() > GROUP_LIMIT {
            out.push_str(&format!(
                "<p class=\"note\">{} more <code>{}</code> rows in this file are in the JSON and SARIF reports.</p>",
                group.rows.len() - GROUP_LIMIT,
                esc(group.rule)
            ));
        }
        out.push_str("</div>");
    }
    out.push_str("</div></details>\n");
}

/// Stable, unique anchor per finding id: `f-` plus an FNV-1a hash.
fn anchor(id: &str, taken: &mut Vec<String>) -> String {
    let hash = id.bytes().fold(0xcbf2_9ce4_8422_2325u64, |h, b| {
        (h ^ u64::from(b)).wrapping_mul(0x100_0000_01b3)
    });
    let base = format!("f-{hash:016x}");
    let mut name = base.clone();
    let mut n = 1;
    while taken.contains(&name) {
        n += 1;
        name = format!("{base}-{n}");
    }
    taken.push(name.clone());
    name
}

fn finding_row(out: &mut String, row: &Row, path: &str, anchors: &mut Vec<String>) {
    let f = row.finding;
    let sev = severity(f);
    let id = anchor(&f.id, anchors);
    let line = row.lines.first().copied();
    let location = match line {
        Some(line) => format!("{path}:{line}"),
        None => path.to_string(),
    };
    let search = format!(
        "{location} {} {} {} {}",
        f.rule,
        f.engine,
        f.symbol.as_deref().unwrap_or(""),
        f.message
    )
    .to_lowercase();
    out.push_str(&format!(
        "<article class=\"f s-{sev}\" id=\"{id}\" data-sev=\"{sev}\" data-eng=\"{}\" data-rule=\"{}\" data-n=\"{}\" data-q=\"{}\"><div class=\"f-main\"><span class=\"sev s-{sev}\">{sev}</span><p class=\"msg\">{}</p>",
        esc(&f.engine),
        esc(&f.rule),
        row.count,
        esc(&search),
        esc(&f.message)
    ));
    if row.count > 1 {
        out.push_str(&format!("<span class=\"rep\">×{}</span>", row.count));
    }
    out.push_str("</div><div class=\"f-meta\">");
    if path != REPO_LEVEL {
        out.push_str(&path_html(path, line));
    }
    if row.lines.len() > 1 {
        let more: Vec<String> = row.lines[1..].iter().take(12).map(u32::to_string).collect();
        out.push_str(&format!(
            "<span class=\"lines\">also line {}</span>",
            more.join(", ")
        ));
    }
    if let Some(symbol) = &f.symbol {
        out.push_str(&format!("<code>{}</code>", esc(symbol)));
    }
    out.push_str(&format!("<span>{}</span></div>", esc(&f.engine)));
    finding_extras(out, row);
    out.push_str(&format!(
        "<div class=\"f-act js-only\"><button type=\"button\" data-copy=\"{}\">Copy</button><a href=\"#{id}\">Link</a></div></article>",
        esc(&format!("{location} {} {}", f.rule, f.message))
    ));
}

fn finding_extras(out: &mut String, row: &Row) {
    let f = row.finding;
    let (functions, more) = evidence_functions(f);
    if !functions.is_empty() {
        out.push_str("<ul class=\"fnlist\">");
        for (location, symbol) in &functions {
            out.push_str(&format!(
                "<li>{} <code>{}</code></li>",
                path_html(location, None),
                esc(symbol)
            ));
        }
        if more > 0 {
            out.push_str(&format!("<li>{more} more</li>"));
        }
        out.push_str("</ul>");
    }
    if row.untested {
        out.push_str("<p class=\"note\">Also <code>complexity.untested</code>: no coverage at this complexity.</p>");
    }
    if let Some(action) = &f.suggested_action {
        out.push_str(&format!("<p class=\"fix\"><b>Fix:</b> {}</p>", esc(action)));
    }
    if let Some(log) = raw_log(f) {
        out.push_str(&format!(
            "<details class=\"log\"><summary>Full output</summary><pre>{}</pre></details>",
            esc(log)
        ));
    }
}
/// Functions shown per finding from `evidence.functions`.
const FUNCTION_LIMIT: usize = 20;

/// The functions a finding lists in `evidence.functions` (for example the
/// functions `coverage.unmatched` found no coverage record for), as
/// ("file:line", symbol) pairs, plus how many more exist beyond what is
/// shown. The engine caps the list, so `evidence.unmatched` can give the
/// real total. Empty when the finding already names its one function.
pub(crate) fn evidence_functions(finding: &sc_core::Finding) -> (Vec<(String, String)>, usize) {
    let Some(items) = finding
        .evidence
        .get("functions")
        .and_then(|functions| functions.as_array())
    else {
        return (Vec::new(), 0);
    };
    let listed: Vec<(String, String)> = items
        .iter()
        .filter_map(|item| {
            let file = item.get("file")?.as_str()?;
            let symbol = item.get("symbol")?.as_str()?;
            let line = item
                .get("line")
                .or_else(|| item.get("span").and_then(|span| span.get("start_line")))
                .and_then(|line| line.as_u64());
            let location = match line {
                Some(line) => format!("{file}:{line}"),
                None => file.to_string(),
            };
            Some((location, symbol.to_string()))
        })
        .collect();
    if listed.len() == 1 && finding.symbol.as_deref() == Some(listed[0].1.as_str()) {
        return (Vec::new(), 0);
    }
    let total = finding
        .evidence
        .get("unmatched")
        .and_then(|count| count.as_u64())
        .map(|count| count as usize)
        .unwrap_or(listed.len())
        .max(listed.len());
    let shown: Vec<_> = listed.into_iter().take(FUNCTION_LIMIT).collect();
    let more = total - shown.len();
    (shown, more)
}

/// The raw command output a finding carries in `evidence.log` (lint and
/// test failures). The message is the first useful line; the log sits
/// behind a disclosure so the compile preamble never leads the card.
pub(crate) fn raw_log(finding: &sc_core::Finding) -> Option<&str> {
    finding
        .evidence
        .get("log")
        .and_then(|log| log.as_str())
        .map(str::trim_end)
        .filter(|log| !log.trim().is_empty())
}

fn plural(n: usize, one: &str, many: &str) -> String {
    format!("{n} {}", if n == 1 { one } else { many })
}

fn crap(out: &mut String, card: &Scorecard) {
    out.push_str(&format!(
        "<section id=\"crap\" aria-labelledby=\"crap-h\"><h2 id=\"crap-h\">worst crap · threshold {}</h2><div class=\"card\">",
        card.crap.threshold
    ));
    if !ran(card, &["crap"]) {
        out.push_str("<p class=\"note\">Not measured: the crap engine did not run. See Engines below for why.</p></div></section>\n");
        return;
    }
    if let Some(line) = diff_baseline(card) {
        out.push_str(&format!("<p class=\"note\">{}</p>", esc(&line)));
    }
    let measured = coverage_measured(card);
    if !measured {
        out.push_str(&format!("<p class=\"note\">{COVERAGE_NOT_MEASURED}</p>"));
    }
    if card.crap.worst.is_empty() {
        out.push_str(
            "<p class=\"note\">No functions in the reporting window.</p></div></section>\n",
        );
        return;
    }
    out.push_str("<table class=\"stack\"><colgroup><col class=\"c-num\"><col class=\"c-num\"><col class=\"c-cov\"><col><col></colgroup><thead><tr><th scope=\"col\">CRAP</th><th scope=\"col\">CC</th><th scope=\"col\">coverage</th><th scope=\"col\">symbol</th><th scope=\"col\">file</th></tr></thead><tbody>");
    let repo = card.repo.as_str();
    for row in &card.crap.worst {
        let over = row.crap > f64::from(card.crap.threshold);
        let cov = (row.coverage.clamp(0.0, 1.0) * 100.0).round() as i64;
        let coverage = if measured {
            format!(
                "<div class=\"cov\"><span class=\"bar\" aria-hidden=\"true\"><i class=\"{}\" style=\"width:{cov}%\"></i></span><small>{cov}%</small></div>",
                level(row.coverage)
            )
        } else {
            "<span class=\"nm\">not measured</span>".to_string()
        };
        out.push_str(&format!(
            "<tr><td data-label=\"CRAP\"><span class=\"pill p-{}\">{}</span></td><td data-label=\"CC\">{}</td><td data-label=\"coverage\">{coverage}</td><td data-label=\"symbol\"><code>{}</code></td><td data-label=\"file\">{}</td></tr>",
            if over { "error" } else { "info" },
            esc(&fmt_num(row.crap)),
            row.cc,
            esc(&row.symbol),
            path_html(&rel_path(&row.file, repo), None)
        ));
    }
    out.push_str("</tbody></table></div></section>\n");
}

/// Why an engine did not run, and the command or setting that runs it.
fn skip_reason(card: &Scorecard, engine: &str) -> (String, Option<String>) {
    if let Some(f) = card
        .findings
        .iter()
        .find(|f| f.engine == engine && f.rule == "engine.unavailable")
    {
        return (f.message.clone(), f.suggested_action.clone());
    }
    match engine {
        "spec" => (
            "No spec file was given.".into(),
            Some("sc analyze . --spec TASK.md".into()),
        ),
        "mutation" => (
            "Mutation testing is off by default.".into(),
            Some("sc analyze . --mutation diff".into()),
        ),
        "llm" => (
            "The model review is off by default.".into(),
            Some("sc analyze . --llm on --spec TASK.md".into()),
        ),
        _ => (format!("The {} pack does not run it.", card.pack), None),
    }
}

fn run_details(out: &mut String, card: &Scorecard) {
    out.push_str("<section id=\"run\" aria-labelledby=\"run-h\"><h2 id=\"run-h\">Run details</h2><div class=\"cards\"><div class=\"card\"><h3>Engines</h3><ul class=\"chips\">");
    for engine in &card.engines_run {
        out.push_str(&format!("<li>{}</li>", esc(engine)));
    }
    out.push_str("</ul>");
    if !card.engines_skipped.is_empty() {
        out.push_str("<h4>Skipped</h4><ul class=\"skips\">");
        for engine in &card.engines_skipped {
            let (why, fix) = skip_reason(card, engine);
            out.push_str(&format!("<li><code>{}</code> {}", esc(engine), esc(&why)));
            if let Some(fix) = fix {
                out.push_str(&format!(
                    "<span class=\"fixcmd\">To run it: <code>{}</code></span>",
                    esc(&fix)
                ));
            }
            out.push_str("</li>");
        }
        out.push_str("</ul>");
    }
    out.push_str("</div>");
    scope_card(out, card);
    deep_card(out, card);
    runs(out, card);
    out.push_str("</div></section>\n");
}

fn scope_card(out: &mut String, card: &Scorecard) {
    out.push_str(&format!(
        "<div class=\"card\"><h3>Scope</h3><p><code>{}</code>",
        esc(&card.scope.mode)
    ));
    if let Some(base) = &card.scope.base {
        out.push_str(&format!(" against <code>{}</code>", esc(base)));
    }
    out.push_str("</p>");
    if let Some(intent) = card
        .intent
        .as_deref()
        .map(str::trim)
        .filter(|i| !i.is_empty())
    {
        out.push_str(&format!("<p>Intent: {}</p>", esc(intent)));
    }
    let paths = &card.scope.paths;
    if !paths.is_empty() {
        out.push_str(&format!(
            "<details><summary>{}</summary><ul class=\"pathlist\">",
            plural(paths.len(), "path", "paths")
        ));
        for path in paths {
            out.push_str(&format!(
                "<li>{}</li>",
                path_html(&rel_path(path, &card.repo), None)
            ));
        }
        out.push_str("</ul></details>");
    }
    out.push_str("</div>");
}

fn deep_card(out: &mut String, card: &Scorecard) {
    out.push_str("<div class=\"card\"><h3>Spec and mutation</h3>");
    match &card.spec.path {
        Some(path) => {
            out.push_str(&format!(
                "<p>Spec {} · {}</p>",
                path_html(path, None),
                plural(card.spec.gaps.len(), "gap", "gaps")
            ));
            for gap in &card.spec.gaps {
                out.push_str(&format!("<pre>{}</pre>", esc(&gap.to_string())));
            }
        }
        None => out.push_str("<p class=\"note\">Spec: not requested.</p>"),
    }
    let m = &card.mutation;
    if m.status == "skipped" || m.status == "off" {
        out.push_str("<p class=\"note\">Mutation: not run.</p>");
    } else {
        out.push_str(&format!(
            "<p>Mutation {}{}: {} killed, {} survived, {} timed out.</p>",
            esc(&m.status),
            m.score
                .map(|s| format!(", score {s:.2}"))
                .unwrap_or_default(),
            m.killed,
            m.survived,
            m.timeout
        ));
    }
    out.push_str("</div>");
}

fn runs(out: &mut String, card: &Scorecard) {
    out.push_str("<div class=\"card wide\"><h3>Commands</h3>");
    if card.runs.is_empty() {
        out.push_str("<p class=\"note\">No external commands ran.</p></div>");
        return;
    }
    out.push_str("<table class=\"stack\"><colgroup><col class=\"c-eng\"><col><col class=\"c-exit\"><col class=\"c-ms\"></colgroup><thead><tr><th scope=\"col\">engine</th><th scope=\"col\">command</th><th scope=\"col\">exit</th><th scope=\"col\">ms</th></tr></thead><tbody>");
    for run in &card.runs {
        let exit = match run.exit_code {
            Some(0) => "<span class=\"pill p-info\">0</span>".to_string(),
            Some(code) => format!("<span class=\"pill p-error\">{code}</span>"),
            None => "<span class=\"nm\">none</span>".to_string(),
        };
        out.push_str(&format!(
            "<tr><td data-label=\"engine\"><code>{}</code></td><td data-label=\"command\"><pre>{}</pre></td><td data-label=\"exit\">{exit}</td><td data-label=\"ms\">{}</td></tr>",
            esc(&run.engine),
            esc(&run.command),
            run.duration_ms
        ));
    }
    out.push_str("</tbody></table></div>");
}

fn esc(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_core::{CrapFunction, CrapSection, Gate, Span};

    fn card() -> Scorecard {
        let mut card = Scorecard::skeleton("testdata/<good>&\"crate\"", 30);
        card.verdict = "fail".into();
        card.engines_run = vec!["compile".into(), "tests".into(), "crap".into()];
        card.gates.push(Gate {
            id: "crap".into(),
            pass: false,
            enforced: true,
            reason: Some("1 function over threshold".into()),
        });
        card.crap = CrapSection {
            threshold: 30,
            worst: vec![CrapFunction {
                symbol: "classify".into(),
                file: "src/lib.rs".into(),
                cc: 11,
                coverage: 0.0,
                crap: 132.0,
            }],
        };
        card.findings.push(finding(
            "crap.over_threshold",
            "crap",
            "error",
            "src/lib.rs",
            "classify",
        ));
        card
    }

    fn finding(rule: &str, engine: &str, severity: &str, file: &str, symbol: &str) -> Finding {
        Finding {
            id: format!("{engine}:{file}:{symbol}"),
            rule: rule.into(),
            engine: engine.into(),
            severity: severity.into(),
            file: file.into(),
            span: None,
            symbol: (!symbol.is_empty()).then(|| symbol.to_string()),
            message: format!("{rule} on {symbol}"),
            evidence: serde_json::json!({}),
            suggested_action: None,
            disposition: String::new(),
        }
    }

    fn at(mut f: Finding, line: u32) -> Finding {
        f.span = Some(Span {
            start_line: line,
            start_col: 1,
            end_line: line,
            end_col: 1,
        });
        f
    }

    #[test]
    fn verdict_names_the_failing_gates() {
        let mut c = card();
        c.gates.push(Gate {
            id: "tests".into(),
            pass: false,
            enforced: true,
            reason: None,
        });
        let html = to_html(&c);
        assert!(html.contains("FAIL</h1>"));
        assert!(html.contains("2 gates (crap, tests) failed."));
    }

    #[test]
    fn report_only_and_advisory_verdicts_say_why() {
        let mut c = card();
        c.verdict = "pass".into();
        c.gates[0].enforced = false;
        let html = to_html(&c);
        assert!(html.contains("REPORT ONLY</h1>"));
        assert!(html.contains(
            "No gate is enforced in this run, so it passes. 1 gate (crap) would fail if enforced."
        ));
        assert!(html.contains("— report only</title>"));
        c.gates.push(Gate {
            id: "types".into(),
            pass: true,
            enforced: true,
            reason: None,
        });
        let html = to_html(&c);
        assert!(html.contains("PASS</h1>"));
        assert!(html.contains("Enforced gates passed. 1 gate (crap) advisory and failing."));
    }

    #[test]
    fn unmeasured_scores_and_tiles_say_not_measured() {
        let html = to_html(&card());
        // compile and crap ran; perf, secrets/sca, a11y and coverage did not.
        assert!(
            html.contains("<span>correctness</span><span class=\"bar\" aria-hidden=\"true\"><i")
        );
        assert!(html.contains("<span>a11y</span><span class=\"bar\" aria-hidden=\"true\"></span><span class=\"sval nm\" title=\"a11y did not run\">not measured</span>"));
        assert!(html.contains("<li><b class=\"nm\">not measured</b><span>coverage</span></li>"));
        assert!(
            html.contains("<li><b class=\"nm\">not measured</b><span>undeclared deps</span></li>")
        );
        // crap ran, so its tiles show numbers.
        assert!(html.contains("<li><b>0</b><span>CRAP max</span></li>"));
        assert!(html.contains("CRAP assumes 0% coverage"));
    }

    #[test]
    fn crap_section_says_not_measured_when_crap_did_not_run() {
        let mut c = card();
        c.engines_run.retain(|e| e != "crap");
        let html = to_html(&c);
        assert!(html.contains("Not measured: the crap engine did not run."));
        assert!(!html.contains("<th scope=\"col\">CRAP</th>"));
    }

    #[test]
    fn findings_group_by_file_then_rule_with_errors_first() {
        let mut c = card();
        c.findings.push(finding(
            "perf.nested_loop",
            "perf",
            "warning",
            "src/a.rs",
            "a",
        ));
        c.findings.push(finding(
            "crap.over_threshold",
            "crap",
            "error",
            "src/lib.rs",
            "run",
        ));
        c.findings.push(finding(
            "test.failed",
            "tests",
            "error",
            "src/lib.rs",
            "it_adds",
        ));
        c.findings.push(finding(
            "engine.unavailable",
            "coverage",
            "warning",
            ".",
            "",
        ));
        let html = to_html(&c);
        let repo = html.find(">(repository)</span>").unwrap();
        let lib = html.find(">lib.rs</span>").unwrap();
        let a = html.find(">a.rs</span>").unwrap();
        assert!(
            repo < lib && lib < a,
            "repository, then the file with errors, then warnings"
        );
        let test = html.find("<code>test.failed</code>").unwrap();
        let crap = html.find("<code>crap.over_threshold</code>").unwrap();
        assert!(test < crap, "rules with errors, smallest first");
        assert!(html.contains("<span class=\"pill p-error\">3 errors</span>"));
    }

    #[test]
    fn repeated_messages_collapse_into_one_row() {
        let mut c = card();
        c.findings.clear();
        for line in [40, 12, 88] {
            c.findings.push(at(
                finding("perf.clone_in_loop", "perf", "warning", "src/a.rs", "run"),
                line,
            ));
        }
        let html = to_html(&c);
        assert_eq!(html.matches("<article class=\"f").count(), 1);
        assert!(html.contains("data-n=\"3\""));
        assert!(html.contains("<span class=\"rep\">×3</span>"));
        assert!(html.contains("src/a.rs:12"));
        assert!(html.contains("also line 40, 88"));
    }

    #[test]
    fn untested_folds_into_the_matching_crap_row() {
        let mut c = card();
        c.findings.push(finding(
            "complexity.untested",
            "complexity",
            "error",
            "src/lib.rs",
            "classify",
        ));
        c.findings.push(finding(
            "complexity.untested",
            "complexity",
            "error",
            "src/lib.rs",
            "other",
        ));
        let html = to_html(&c);
        assert!(html.contains("Also <code>complexity.untested</code>"));
        assert!(html.contains("1 complexity.untested finding is folded"));
        assert_eq!(html.matches("data-rule=\"complexity.untested\"").count(), 1);
    }

    #[test]
    fn group_rows_are_capped() {
        let mut c = card();
        c.findings.clear();
        for i in 0..60 {
            c.findings.push(finding(
                "crap.over_threshold",
                "crap",
                "error",
                "src/lib.rs",
                &format!("f{i}"),
            ));
        }
        let html = to_html(&c);
        assert_eq!(html.matches("<article class=\"f").count(), GROUP_LIMIT);
        assert!(html.contains("10 more <code>crap.over_threshold</code> rows"));
        assert!(
            !html.contains("<details class=\"fg\" open>"),
            "large error groups start closed"
        );
    }

    #[test]
    fn anchors_are_stable_unique_and_copy_the_full_location() {
        let mut taken = Vec::new();
        let a = anchor("crap:src/lib.rs:classify", &mut taken);
        let b = anchor("crap:src/lib.rs:classify", &mut taken);
        assert!(a.starts_with("f-") && a.len() == 18);
        assert_eq!(b, format!("{a}-2"));
        let mut again = Vec::new();
        assert_eq!(anchor("crap:src/lib.rs:classify", &mut again), a);
        let mut c = card();
        c.findings[0] = at(c.findings[0].clone(), 7);
        let html = to_html(&c);
        assert!(html.contains(&format!("id=\"{a}\"")));
        assert!(html.contains(&format!("<a href=\"#{a}\">Link</a>")));
        assert!(html.contains(
            "data-copy=\"src/lib.rs:7 crap.over_threshold crap.over_threshold on classify\""
        ));
    }

    #[test]
    fn paths_are_relative_and_middle_elided() {
        assert_eq!(rel_path("/work/repo/src/a.rs", "/work/repo"), "src/a.rs");
        assert_eq!(rel_path("./src/a.rs", "."), "src/a.rs");
        assert_eq!(rel_path(".", "."), REPO_LEVEL);
        assert_eq!(
            path_html("infra/cdk.out/asset.c936/x.py", Some(3)),
            "<span class=\"path\" title=\"infra/cdk.out/asset.c936/x.py:3\"><span class=\"ph\">infra/cdk.out/asset.c936/</span><span class=\"pt\">x.py:3</span></span>"
        );
        assert_eq!(
            path_html("lib.rs", None),
            "<span class=\"path\" title=\"lib.rs\"><span class=\"pt\">lib.rs</span></span>"
        );
    }

    #[test]
    fn long_strings_wrap_or_elide_so_nothing_scrolls_sideways() {
        let hash = "c9360261a1ec36ad194552ee4968ce6b5da156849d62a9a24254e6aa0c66aae1";
        let file = format!("infra/cdk.out/asset.{hash}/vectorvault/memory_client.py");
        let mut c = card();
        let mut f = finding(
            "crap.over_threshold",
            "crap",
            "warning",
            &file,
            "MemoryClient.pin_working_set",
        );
        f.id = format!("crap:{file}:MemoryClient.pin_working_set");
        f.message = format!("token {hash}{hash} in {file}");
        c.findings.push(f);
        c.git.head = Some(hash.into());
        let html = to_html(&c);
        // Every long path is an elided .path box with the full value on hover.
        assert!(html.contains(&format!("title=\"{file}\"")));
        assert!(html.contains(&format!(
            "<span class=\"ph\">infra/cdk.out/asset.{hash}/vectorvault/</span>"
        )));
        // Everything else wraps anywhere, and every nowrap rule clips.
        assert!(CSS.contains("html,body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 var(--sans);\noverflow-wrap:anywhere}"));
        assert!(CSS.contains("pre{white-space:pre-wrap;overflow-wrap:anywhere;margin:0}"));
        for rule in CSS.split('}').filter(|r| r.contains("white-space:nowrap")) {
            let bounded = rule.contains("overflow:hidden")
                || rule.starts_with("\n.pill{")
                || rule.contains(".sr-only");
            assert!(bounded, "nowrap without clipping: {rule}");
        }
        // No layout width cap: the page is fluid.
        assert!(!CSS.contains("max-width:880px"));
        // Tables stack into label/value rows on phones.
        assert!(CSS.contains("table.stack td::before{content:attr(data-label)"));
    }

    #[test]
    fn untrusted_text_is_escaped_and_the_page_stays_offline() {
        let mut c = card();
        c.findings[0].message = "<script>alert(1)</script>".into();
        let html = to_html(&c);
        assert!(html.contains("testdata/&lt;good&gt;&amp;&quot;crate&quot;"));
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(!html.contains("<good>"));
        for marker in ["http://", "https://", "//cdn", "<link ", " src="] {
            assert!(!html.contains(marker), "report must not fetch {marker}");
        }
    }

    #[test]
    fn skipped_engines_say_why_and_how_to_run_them() {
        let mut c = card();
        c.engines_skipped = vec!["mutation".into(), "coverage".into()];
        let mut missing = finding("engine.unavailable", "coverage", "warning", ".", "");
        missing.message = "pytest-cov did not report line coverage".into();
        missing.suggested_action = Some("Install pytest-cov and re-run".into());
        c.findings.push(missing);
        let html = to_html(&c);
        assert!(html.contains("<code>mutation</code> Mutation testing is off by default.<span class=\"fixcmd\">To run it: <code>sc analyze . --mutation diff</code></span>"));
        assert!(html.contains("<code>coverage</code> pytest-cov did not report line coverage<span class=\"fixcmd\">To run it: <code>Install pytest-cov and re-run</code></span>"));
        assert!(html.contains("Mutation: not run."));
        assert!(!html.contains("0 killed"));
    }

    #[test]
    fn diff_scope_prints_the_diff_count_and_points_at_the_base() {
        let mut c = card();
        c.scope.mode = "diff".into();
        c.scope.base = Some("origin/main".into());
        c.metrics.crap_over_threshold = 4;
        assert!(to_html(&c).contains("diff scope: 4 functions over threshold in this diff. The tree-wide count is on the latest push run of main."));
        c.scope.base = Some("HEAD~1".into());
        c.metrics.crap_over_threshold = 1;
        assert!(to_html(&c).contains("a tree-scope run (sc analyze without --diff)"));
        c.scope.mode = "tree".into();
        assert!(!to_html(&c).contains("diff scope:"));
    }

    #[test]
    fn evidence_functions_and_logs_render_under_the_finding() {
        let mut c = card();
        let mut unmatched = finding("coverage.unmatched", "coverage", "warning", ".", "");
        unmatched.evidence = serde_json::json!({
            "unmatched": 25,
            "functions": [{"file": "src/a.rs", "symbol": "a::run", "line": 12}, {"file": "src/b.rs", "symbol": "b<T>::go"}],
            "log": "   Compiling demo\nerror: boom <T>\n",
        });
        c.findings.push(unmatched);
        let html = to_html(&c);
        assert!(html.contains("<li><span class=\"path\" title=\"src/a.rs:12\">"));
        assert!(html.contains("<code>b&lt;T&gt;::go</code>"));
        assert!(html.contains("<li>23 more</li>"));
        assert!(html.contains("<details class=\"log\"><summary>Full output</summary><pre>   Compiling demo\nerror: boom &lt;T&gt;</pre></details>"));
        let mut one = card();
        let mut single = finding(
            "coverage.unmatched",
            "coverage",
            "warning",
            "src/a.rs",
            "a::run",
        );
        single.evidence = serde_json::json!({"unmatched": 1, "functions": [{"file": "src/a.rs", "symbol": "a::run", "line": 12}]});
        one.findings.push(single);
        assert!(!to_html(&one).contains("class=\"fnlist\""));
    }

    #[test]
    fn clean_run_says_so_and_skips_the_filters() {
        let mut c = card();
        c.verdict = "pass".into();
        c.gates[0].pass = true;
        c.findings.clear();
        let html = to_html(&c);
        assert!(html.contains("PASS</h1>"));
        assert!(html.contains("Every gate that ran passed."));
        assert!(html.contains("No findings. Every engine that ran came back clean."));
        assert!(!html.contains("id=\"q\""));
    }

    #[test]
    fn unprovided_gates_render_as_skipped_outside_the_ratio() {
        let mut c = card();
        c.gates.push(Gate {
            id: "sca".into(),
            pass: false,
            enforced: false,
            reason: Some(NOT_PROVIDED.into()),
        });
        let html = to_html(&c);
        assert!(html.contains("<code>sca</code><span class=\"tag\">skipped</span><span class=\"sr-only\">skipped</span></li>"));
        assert!(html.contains("<b>gates</b><span>0/1 pass</span>"));
    }

    #[test]
    fn long_sha_shows_short_with_the_full_value_on_hover() {
        let mut c = card();
        let full = "0123456789abcdef0123456789abcdef01234567";
        c.git.head = Some(full.into());
        c.git.dirty = true;
        let html = to_html(&c);
        assert!(html.contains(&format!(
            "<code title=\"{full}\">{}</code> dirty",
            &full[..12]
        )));
    }
}
