//! Self-contained HTML scorecard report.
//!
//! `to_html` renders one `.html` file with inline CSS and no external
//! requests, so it works from `file://` and from any static server.
//! It mirrors the linear-flow visual language: pipeline strip, in/out
//! chips, terminal-styled runs, and pass/fail pills.

use sc_core::Scorecard;

pub fn to_html(card: &Scorecard) -> String {
    let mut out = String::new();
    out.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\"/>\n");
    out.push_str(
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n<title>",
    );
    out.push_str(&esc(&format!("scorecard: {} — {}", card.repo, card.verdict)));
    out.push_str("</title>\n<style>\n");
    out.push_str(CSS);
    out.push_str("\n</style>\n</head>\n<body>\n<main>\n");
    hero(&mut out, card);
    pipeline(&mut out, card);
    scores_metrics(&mut out, card);
    gates(&mut out, card);
    crap(&mut out, card);
    findings(&mut out, card);
    deep(&mut out, card);
    runs(&mut out, card);
    out.push_str("<footer>generated by <code>sc analyze --format html</code> · scorecard ");
    out.push_str(&esc(&card.id));
    out.push_str(" · schema ");
    out.push_str(&esc(&card.version));
    out.push_str("</footer>\n</main>\n</body>\n</html>\n");
    out
}

const CSS: &str = r#"
:root{--bg:#070b14;--card:#0b1428;--line:#22314f;--ink:#e8eefc;--dim:#8fa1c7;
--accent:#6ea8ff;--ok:#59e3a5;--bad:#ff7a90;--warn:#ffcf6e}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
main{max-width:880px;margin:0 auto;padding:28px 20px 60px}
h1{font-size:22px;margin:0}
h2{font-size:15px;margin:28px 0 10px;color:var(--dim);text-transform:uppercase;
letter-spacing:.08em}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;
padding:16px 18px;margin-top:12px}
.hero{display:flex;gap:16px;align-items:center;flex-wrap:wrap}
.verdict{font-size:15px;font-weight:800;border-radius:999px;padding:8px 22px;
letter-spacing:.06em}
.verdict.pass{background:rgba(89,227,165,.14);color:var(--ok);
border:1px solid var(--ok)}
.verdict.fail{background:rgba(255,122,144,.12);color:var(--bad);
border:1px solid var(--bad)}
.meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
gap:8px 20px;margin-top:14px;font-size:12.5px;color:var(--dim)}
.meta b{color:var(--ink);font-weight:600}
.meta code,.card code{background:#16223f;padding:1px 6px;border-radius:6px;
font-size:11.5px;color:var(--ink)}
.flow{display:flex;align-items:stretch;gap:0;margin-top:12px;flex-wrap:wrap}
.step{flex:1 1 0;min-width:120px;background:var(--card);
border:1px solid var(--line);border-radius:10px;padding:10px 12px;font-size:12px}
.step b{display:block;font-size:12.5px;margin-bottom:2px}
.step span{color:var(--dim);font-size:11.5px}
.step.hi{border-color:var(--accent)}
.sep{align-self:center;color:#3a5086;font-size:18px;padding:0 6px}
.pill{display:inline-block;font-size:11px;border-radius:999px;
padding:2px 10px;border:1px solid #3a5086;color:#bcd0ff;white-space:nowrap}
.pill.pass{border-color:var(--ok);color:var(--ok)}
.pill.fail{border-color:var(--bad);color:var(--bad)}
.pill.warn{border-color:var(--warn);color:var(--warn)}
.pill.info{border-color:var(--accent);color:#c9d9ff}
.pill.dim{color:var(--dim)}
table{width:100%;border-collapse:collapse;font-size:12.5px}
th{text-align:left;color:var(--dim);font-weight:600;font-size:11px;
text-transform:uppercase;letter-spacing:.06em;padding:6px 8px;
border-bottom:1px solid var(--line)}
td{padding:7px 8px;border-bottom:1px solid #16223f;vertical-align:top}
tr:last-child td{border-bottom:none}
.bar{height:8px;border-radius:4px;background:#16223f;overflow:hidden;
min-width:90px}
.bar i{display:block;height:100%;border-radius:4px}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));
gap:10px;margin-top:12px}
.tile{background:var(--card);border:1px solid var(--line);border-radius:12px;
padding:10px 14px}
.tile b{display:block;font-size:20px}
.tile span{font-size:11px;color:var(--dim)}
.finding{border-left:4px solid var(--warn)}
.finding.error{border-left-color:var(--bad)}
.finding h3{margin:0 0 6px;font-size:13px;font-family:ui-monospace,Menlo,monospace;
font-weight:600;word-break:break-all}
.finding p{margin:6px 0;font-size:13px}
.finding .row{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:6px}
.suggest{color:var(--dim);font-size:12.5px}
.term{background:#04080f;border:1px solid #1b2a4e;border-radius:10px;
padding:8px 12px;margin:8px 0 0;font-family:ui-monospace,Menlo,monospace;
font-size:11.5px;overflow-x:auto;white-space:nowrap}
.term b{color:var(--ok)}
footer{margin-top:32px;color:var(--dim);font-size:11.5px;text-align:center}
"#;

fn hero(out: &mut String, card: &Scorecard) {
    let pass = card.verdict == "pass";
    out.push_str("<h1>scorecard</h1>\n<div class=\"card\"><div class=\"hero\">");
    out.push_str(&format!(
        "<span class=\"verdict {}\">{}</span>",
        if pass { "pass" } else { "fail" },
        esc(&card.verdict.to_uppercase())
    ));
    out.push_str("<div><div style=\"font-size:16px;font-weight:700\">");
    out.push_str(&esc(&card.repo));
    out.push_str("</div><div style=\"font-size:12px;color:var(--dim)\">pack <code>");
    out.push_str(&esc(&card.pack));
    out.push_str("</code> · scope <code>");
    out.push_str(&esc(&card.scope.mode));
    out.push_str("</code> · <code>");
    out.push_str(&esc(&card.id));
    out.push_str("</code></div></div></div><div class=\"meta\">");
    meta(out, "git", &git(card));
    meta(out, "tests", &esc(&card.test_selection));
    meta(
        out,
        "engines run",
        &esc(&if card.engines_run.is_empty() {
            "—".into()
        } else {
            card.engines_run.join(", ")
        }),
    );
    meta(
        out,
        "engines skipped",
        &esc(&if card.engines_skipped.is_empty() {
            "—".into()
        } else {
            card.engines_skipped.join(", ")
        }),
    );
    if let Some(intent) = &card.intent {
        if !intent.trim().is_empty() {
            meta(out, "intent", &esc(intent.trim()));
        }
    }
    if !card.scope.paths.is_empty() {
        meta(out, "paths", &esc(&card.scope.paths.join(", ")));
    }
    out.push_str("</div></div>\n");
}

fn meta(out: &mut String, label: &str, value: &str) {
    out.push_str("<div><b>");
    out.push_str(label);
    out.push_str("</b><br/>");
    out.push_str(value);
    out.push_str("</div>");
}

fn git(card: &Scorecard) -> String {
    let head = card.git.head.as_deref().unwrap_or("none");
    let state = if card.git.dirty { "dirty" } else { "clean" };
    esc(&format!("{head} ({state})"))
}

fn pipeline(out: &mut String, card: &Scorecard) {
    let passed = card.gates.iter().filter(|gate| gate.pass).count();
    out.push_str("<h2>flow</h2>\n<div class=\"flow\">");
    step(
        out,
        "scope",
        &card.scope.mode,
        card.scope.paths.len(),
        false,
    );
    step(out, "pack", &card.pack, 0, false);
    step(
        out,
        "engines",
        &format!("{} run", card.engines_run.len()),
        card.engines_skipped.len(),
        false,
    );
    step(
        out,
        "gates",
        &format!("{passed}/{} pass", card.gates.len()),
        0,
        true,
    );
    out.push_str("<div class=\"sep\">→</div>");
    out.push_str("<div class=\"step");
    if card.verdict == "pass" {
        out.push_str(" hi");
    }
    out.push_str("\"><b>verdict</b><span>");
    out.push_str(&esc(&card.verdict));
    out.push_str("</span></div></div>\n");
}

fn step(out: &mut String, title: &str, main: &str, skipped: usize, hi: bool) {
    if !out.ends_with("<div class=\"flow\">") {
        out.push_str("<div class=\"sep\">→</div>");
    }
    out.push_str("<div class=\"step");
    if hi {
        out.push_str(" hi");
    }
    out.push_str("\"><b>");
    out.push_str(title);
    out.push_str("</b><span>");
    out.push_str(&esc(main));
    if skipped > 0 {
        out.push_str(&format!(" · {skipped} skipped"));
    }
    out.push_str("</span></div>");
}

fn scores_metrics(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>scores</h2>\n<div class=\"card\"><table>");
    for (label, value) in [
        ("correctness", card.scores.correctness),
        ("efficiency", card.scores.efficiency),
        ("maintainability", card.scores.maintainability),
        ("security", card.scores.security),
    ] {
        let pct = (value.clamp(0.0, 1.0) * 100.0).round() as i64;
        out.push_str(&format!(
            "<tr><td style=\"width:140px\">{label}</td><td><div class=\"bar\"><i style=\"width:{pct}%;background:{}\"></i></div></td><td style=\"width:60px\">{value:.2}</td></tr>",
            score_color(value)
        ));
    }
    out.push_str("</table></div>\n<div class=\"tiles\">");
    tile(out, card.metrics.loc_changed.to_string(), "loc changed");
    tile(out, card.metrics.files_changed.to_string(), "files changed");
    tile(
        out,
        format!("{:.0}%", card.metrics.coverage_changed * 100.0),
        "coverage",
    );
    tile(out, fmt_num(card.metrics.crap_max), "crap max");
    tile(
        out,
        card.metrics.crap_over_threshold.to_string(),
        "over threshold",
    );
    tile(
        out,
        card.metrics.hallucinated_imports.to_string(),
        "hallucinated imports",
    );
    out.push_str("</div>\n");
}

fn tile(out: &mut String, value: String, label: &str) {
    out.push_str("<div class=\"tile\"><b>");
    out.push_str(&esc(&value));
    out.push_str("</b><span>");
    out.push_str(label);
    out.push_str("</span></div>");
}

fn gates(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>gates</h2>\n<div class=\"card\"><table>");
    out.push_str("<tr><th>gate</th><th>result</th><th>enforced</th><th>reason</th></tr>");
    for gate in &card.gates {
        out.push_str("<tr><td><code>");
        out.push_str(&esc(&gate.id));
        out.push_str("</code></td><td>");
        if gate.pass {
            out.push_str("<span class=\"pill pass\">pass</span>");
        } else {
            out.push_str("<span class=\"pill fail\">fail</span>");
        }
        out.push_str("</td><td>");
        if gate.enforced {
            out.push_str("yes");
        } else {
            out.push_str("<span class=\"pill dim\">reported only</span>");
        }
        out.push_str("</td><td>");
        out.push_str(&esc(gate.reason.as_deref().unwrap_or("")));
        out.push_str("</td></tr>");
    }
    out.push_str("</table></div>\n");
}

fn crap(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>worst crap · threshold ");
    out.push_str(&card.crap.threshold.to_string());
    out.push_str("</h2>\n<div class=\"card\"><table>");
    out.push_str("<tr><th>crap</th><th>cc</th><th>coverage</th><th>symbol</th><th>file</th></tr>");
    if card.crap.worst.is_empty() {
        out.push_str("<tr><td colspan=\"5\" style=\"color:var(--dim)\">No functions over the reporting window.</td></tr>");
    }
    for row in &card.crap.worst {
        let over = row.crap > card.crap.threshold as f64;
        let cov = (row.coverage.clamp(0.0, 1.0) * 100.0).round() as i64;
        out.push_str("<tr><td><span class=\"pill ");
        out.push_str(if over { "fail" } else { "pass" });
        out.push_str("\">");
        out.push_str(&esc(&fmt_num(row.crap)));
        out.push_str("</span></td><td>");
        out.push_str(&row.cc.to_string());
        out.push_str("</td><td><div class=\"bar\"><i style=\"width:");
        out.push_str(&cov.to_string());
        out.push_str("%;background:");
        out.push_str(score_color(row.coverage));
        out.push_str("\"></i></div></td><td><code>");
        out.push_str(&esc(&row.symbol));
        out.push_str("</code></td><td><code>");
        out.push_str(&esc(&row.file));
        out.push_str("</code></td></tr>");
    }
    out.push_str("</table></div>\n");
}

fn findings(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>findings · ");
    out.push_str(&card.findings.len().to_string());
    out.push_str("</h2>\n");
    if card.findings.is_empty() {
        out.push_str("<div class=\"card\" style=\"color:var(--dim)\">None. Clean gate.</div>\n");
        return;
    }
    for finding in &card.findings {
        let cls = if finding.severity == "error" {
            "finding error"
        } else {
            "finding"
        };
        out.push_str("<div class=\"card ");
        out.push_str(cls);
        out.push_str("\"><h3>");
        out.push_str(&esc(&finding.id));
        out.push_str("</h3><div class=\"row\">");
        out.push_str("<span class=\"pill ");
        out.push_str(if finding.severity == "error" {
            "fail"
        } else {
            "warn"
        });
        out.push_str("\">");
        out.push_str(&esc(&finding.severity));
        out.push_str("</span><span class=\"pill info\">");
        out.push_str(&esc(&finding.rule));
        out.push_str("</span>");
        if !finding.disposition.is_empty() {
            out.push_str("<span class=\"pill dim\">");
            out.push_str(&esc(&finding.disposition));
            out.push_str("</span>");
        }
        out.push_str("<span class=\"pill dim\">");
        out.push_str(&esc(&finding.engine));
        out.push_str("</span></div><p>");
        out.push_str(&esc(&finding.message));
        out.push_str("</p><div style=\"font-size:12px;color:var(--dim)\">");
        out.push_str(&esc(&finding.file));
        if let Some(span) = &finding.span {
            out.push_str(&format!(":{}:{}", span.start_line, span.start_col));
        }
        if let Some(symbol) = &finding.symbol {
            out.push_str(" · <code>");
            out.push_str(&esc(symbol));
            out.push_str("</code>");
        }
        out.push_str("</div>");
        if let Some(action) = &finding.suggested_action {
            out.push_str("<div class=\"suggest\">suggested: ");
            out.push_str(&esc(action));
            out.push_str("</div>");
        }
        out.push_str("</div>\n");
    }
}

fn deep(out: &mut String, card: &Scorecard) {
    let m = &card.mutation;
    out.push_str("<h2>mutation · spec</h2>\n<div class=\"card\"><div class=\"row\" style=\"display:flex;gap:6px;flex-wrap:wrap\">");
    out.push_str("<span class=\"pill info\">");
    out.push_str(&esc(&m.status));
    out.push_str("</span>");
    if let Some(score) = m.score {
        out.push_str("<span class=\"pill dim\">score ");
        out.push_str(&format!("{score:.2}"));
        out.push_str("</span>");
    }
    out.push_str("<span class=\"pill dim\">killed ");
    out.push_str(&m.killed.to_string());
    out.push_str("</span><span class=\"pill dim\">survived ");
    out.push_str(&m.survived.to_string());
    out.push_str("</span><span class=\"pill dim\">timeout ");
    out.push_str(&m.timeout.to_string());
    out.push_str("</span></div>");
    match &card.spec.path {
        Some(path) => {
            out.push_str("<p style=\"font-size:12.5px\">spec <code>");
            out.push_str(&esc(path));
            out.push_str("</code> · gaps ");
            out.push_str(&card.spec.gaps.len().to_string());
            out.push_str("</p>");
            for gap in &card.spec.gaps {
                out.push_str("<div class=\"term\">");
                out.push_str(&esc(&gap.to_string()));
                out.push_str("</div>");
            }
        }
        None => out.push_str(
            "<p style=\"font-size:12.5px;color:var(--dim)\">no spec file requested.</p>",
        ),
    }
    out.push_str("</div>\n");
}

fn runs(out: &mut String, card: &Scorecard) {
    out.push_str("<h2>runs</h2>\n<div class=\"card\"><table>");
    out.push_str("<tr><th>engine</th><th>command</th><th>exit</th><th>ms</th></tr>");
    for run in &card.runs {
        out.push_str("<tr><td><code>");
        out.push_str(&esc(&run.engine));
        out.push_str("</code></td><td><div class=\"term\"><b>$ </b>");
        out.push_str(&esc(&run.command));
        out.push_str("</div></td><td>");
        match run.exit_code {
            Some(0) => out.push_str("<span class=\"pill pass\">0</span>"),
            Some(code) => out.push_str(&format!("<span class=\"pill fail\">{code}</span>")),
            None => out.push_str("<span class=\"pill dim\">—</span>"),
        }
        out.push_str("</td><td>");
        out.push_str(&run.duration_ms.to_string());
        out.push_str("</td></tr>");
    }
    out.push_str("</table></div>\n");
}

fn score_color(value: f64) -> &'static str {
    if value >= 0.9 {
        "#59e3a5"
    } else if value >= 0.7 {
        "#ffcf6e"
    } else {
        "#ff7a90"
    }
}

fn fmt_num(value: f64) -> String {
    if (value - value.round()).abs() < 1e-6 {
        format!("{}", value.round() as i64)
    } else {
        format!("{value:.1}")
    }
}

fn esc(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_core::{CrapFunction, CrapSection, Finding, Gate, Scorecard};

    fn card() -> Scorecard {
        let mut card = Scorecard::skeleton("testdata/<good>&\"crate\"", 30);
        card.verdict = "fail".into();
        card.gates.push(Gate {
            id: "crap".into(),
            pass: false,
            enforced: true,
            reason: Some("1 function over threshold".into()),
        });
        card.crap = CrapSection {
            threshold: 30,
            worst: vec![CrapFunction {
                symbol: "classify".into(),
                file: "src/lib.rs".into(),
                cc: 11,
                coverage: 0.0,
                crap: 132.0,
            }],
        };
        card.findings.push(Finding {
            id: "crap:src/lib.rs:classify".into(),
            rule: "crap.over_threshold".into(),
            engine: "crap".into(),
            severity: "error".into(),
            file: "src/lib.rs".into(),
            span: None,
            symbol: Some("classify".into()),
            message: "CRAP 132 (CC=11, cov=0%) exceeds threshold 30".into(),
            evidence: serde_json::json!({}),
            suggested_action: Some("Add tests covering branches or split the function".into()),
            disposition: "fix".into(),
        });
        card
    }

    #[test]
    fn html_renders_verdict_and_sections() {
        let html = to_html(&card());
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("FAIL"));
        assert!(html.contains("classify"));
        assert!(html.contains("crap.over_threshold"));
        assert!(html.contains("worst crap"));
        assert!(html.contains("runs"));
    }

    #[test]
    fn html_escapes_untrusted_text_and_stays_offline() {
        let html = to_html(&card());
        assert!(html.contains("testdata/&lt;good&gt;&amp;&quot;crate&quot;"));
        assert!(!html.contains("<good>"));
        for marker in ["unpkg", "cdn.", "http://", "https://"] {
            assert!(!html.contains(marker), "report must not fetch {marker}");
        }
    }
}
