[package]
name = "ca-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "sc command line"

[[bin]]
name = "sc"
path = "src/main.rs"

[features]
default = []

[dependencies]
ca-core = { path = "../ca-core" }
ca-engines = { path = "../ca-engines" }
ca-sarif = { path = "../ca-sarif" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
serde_json = "1"
